// Putting a generated stylesheet into a file the user already has — idempotently.
//
// WHY THIS EXISTS (admin 2026-07-27): the Design System and Dark Mode tools both "inject CSS into
// your app", and both did it with a one-off `.replace('</head>', …)` inline in their button handler.
// That was fine while the result only reached the throwaway preview. Now that the result is written
// into the user's REAL file, the same operation has to satisfy two properties those inline versions
// did not:
//
//  • IDEMPOTENT. Pressing the button twice must not stack two copies of the stylesheet. Each block is
//    fenced with a marker so a second run REPLACES the first instead of appending to it. Without this
//    a user who tweaks a colour five times ends up with five conflicting blocks, and the last one
//    silently wins — a bug that is very hard to see and very easy to create.
//
//  • HONEST ABOUT WHAT IT CANNOT DO. Only HTML and CSS files can carry a stylesheet this way. A .tsx
//    file needs an import, not a <style> tag, so we decline instead of producing something that looks
//    applied but is not.
//
// Pure and unit-tested, so both tools get exactly the same behaviour.

export interface InjectionResult {
  ok: boolean;
  /** The updated source. Equals the input when ok is false — never a half-applied edit. */
  code: string;
  /** True when this replaced an earlier block from the same tool rather than adding a new one. */
  replaced: boolean;
  /** Present only when ok is false: why this file cannot carry the stylesheet. */
  error?: string;
}

function fileKind(path: string): 'html' | 'css' | 'other' {
  const ext = (path.split('.').pop() || '').toLowerCase();
  if (ext === 'html' || ext === 'htm') return 'html';
  if (ext === 'css') return 'css';
  return 'other';
}

/** Escape a marker for use inside a RegExp — marker ids are ours, but this keeps the helper safe. */
function esc(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Insert (or update) a fenced stylesheet block in an HTML or CSS file.
 *
 * `markerId` identifies the owning tool, so the Design System's tokens and the Dark Mode stylesheet
 * live side by side and each updates only its own block.
 */
export function injectStyleBlock(
  filePath: string,
  source: string,
  css: string,
  markerId: string,
): InjectionResult {
  const kind = fileKind(filePath);

  if (kind === 'other') {
    return {
      ok: false,
      code: source,
      replaced: false,
      error: 'This stylesheet can only be added to an HTML or CSS file. Pick one of those, or copy the CSS and import it yourself.',
    };
  }

  if (kind === 'css') {
    const start = `/* ${markerId}:start — generated by NavBharatAI. Edit above or below this block. */`;
    const end = `/* ${markerId}:end */`;
    const block = `${start}\n${css}\n${end}`;
    const fence = new RegExp(`${esc(start)}[\\s\\S]*?${esc(end)}`);
    if (fence.test(source)) {
      return { ok: true, code: source.replace(fence, block), replaced: true };
    }
    const separator = source.trim() ? '\n\n' : '';
    return { ok: true, code: `${source.replace(/\s+$/, '')}${separator}${block}\n`, replaced: false };
  }

  // HTML: a single <style> element carrying the id, so a re-run targets exactly this block.
  const tag = `<style id="${markerId}">\n${css}\n</style>`;
  const existing = new RegExp(`<style[^>]*id=["']${esc(markerId)}["'][^>]*>[\\s\\S]*?<\\/style>`, 'i');
  if (existing.test(source)) {
    return { ok: true, code: source.replace(existing, tag), replaced: true };
  }
  if (/<\/head>/i.test(source)) {
    return { ok: true, code: source.replace(/<\/head>/i, `${tag}\n</head>`), replaced: false };
  }
  // No <head> — a fragment or a partial. Prepending still applies the styles to everything below it.
  return { ok: true, code: `${tag}\n${source}`, replaced: false };
}

/** Files this kind of injection can target — used to filter the file picker to honest choices. */
export function canCarryStylesheet(path: string): boolean {
  return fileKind(path) !== 'other';
}

/**
 * Insert (or update) a fenced <script> block in an HTML file, just before </body>.
 *
 * Same reasoning as the stylesheet version, plus one bug it specifically fixes: the Dark Mode tool
 * used to append its toggle-button script AFTER the closing </html> tag, and appended it again on
 * every run. In a preview that was invisible; in a saved file it accumulates a new floating button
 * per press and cannot be removed. Marking the block makes a re-run replace it, and putting it before
 * </body> puts it where a script belongs.
 *
 * Passing an empty `js` REMOVES the block — so switching a strategy off actually takes the script out
 * rather than leaving a dead one behind.
 */
export function injectScriptBlock(
  filePath: string,
  source: string,
  js: string,
  markerId: string,
): InjectionResult {
  if (fileKind(filePath) !== 'html') {
    return {
      ok: false,
      code: source,
      replaced: false,
      error: 'This script can only be added to an HTML file.',
    };
  }

  const existing = new RegExp(`<script[^>]*id=["']${esc(markerId)}["'][^>]*>[\\s\\S]*?<\\/script>\\n?`, 'i');
  const had = existing.test(source);

  if (!js.trim()) {
    return had
      ? { ok: true, code: source.replace(existing, ''), replaced: true }
      : { ok: true, code: source, replaced: false };
  }

  const tag = `<script id="${markerId}">\n${js}\n</script>`;
  if (had) return { ok: true, code: source.replace(existing, `${tag}\n`), replaced: true };
  if (/<\/body>/i.test(source)) {
    return { ok: true, code: source.replace(/<\/body>/i, `${tag}\n</body>`), replaced: false };
  }
  return { ok: true, code: `${source}\n${tag}\n`, replaced: false };
}
