// Safe rendering of (possibly untrusted) SVG source text — generated by Engineer AI, created by the
// user, or pulled from an imported project.
//
// SECURITY: injecting raw SVG source as HTML (dangerouslySetInnerHTML / innerHTML) executes any
// `<script>` or `onerror`/`onload` handler it contains IN THE PLATFORM ORIGIN — a stored XSS that
// can read document.cookie / localStorage (Firebase auth tokens) merely on hover/preview. Loading
// the SVG through an `<img>` data-URI instead makes the browser render it in "secure static mode":
// scripts and event handlers are disabled and external references are blocked, so it can display the
// image but never run code. This is the standard safe way to show untrusted SVG.

/** A script-safe `<img src>` value for previewing arbitrary SVG source text. Pure. */
export function svgPreviewSrc(svgSource: string): string {
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgSource || '')}`;
}
