// AgentV3 — Config engine: .env.example generator (Phase 4 v1).
//
// The classic "your app won't run for anyone else" defect is a missing/incomplete
// `.env.example`: the code reads process.env.X / import.meta.env.X but nothing tells
// the next person which variables to set. `EnvVarAnalysis` already DETECTS this; this
// PURE function GENERATES the fix — a `.env.example` listing every variable the code
// actually references, preserving any values already documented. Derived entirely
// from real references — never invents variables.

/** Parse an existing .env/.env.example into KEY → value, ignoring comments/blanks. */
function parseExisting(raw?: string | null): Map<string, string> {
  const m = new Map<string, string>();
  if (!raw) return m;
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    const key = t.slice(0, eq).trim();
    const val = t.slice(eq + 1).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) m.set(key, val);
  }
  return m;
}

/** Variable NAMES whose value is a secret and must never appear in a committed `.env.example`. */
const SECRET_KEY_RE = /(SECRET|PASSWORD|PASSWD|TOKEN|API[_-]?KEY|PRIVATE[_-]?KEY|ACCESS[_-]?KEY|CLIENT[_-]?SECRET|CREDENTIAL|CONNECTION[_-]?STRING|DSN)/i;

/**
 * Whether a VALUE looks like a real secret (opaque high-entropy string or a URL with embedded
 * credentials) — as opposed to a safe config default (PORT=3000, NODE_ENV=development, a plain URL).
 */
function looksSecretValue(v: string): boolean {
  if (!v) return false;
  if (/^https?:\/\//i.test(v) && !v.includes('@')) return false; // plain URL, no embedded creds → not a secret
  if (/\s/.test(v)) return false;                                  // has spaces → a prose default, not an opaque token
  return v.length >= 24 && /[A-Za-z]/.test(v) && /[0-9]/.test(v);  // long mixed alphanumeric → a key/token/creds URL
}

/**
 * The value to emit for a key in `.env.example` — a COMMITTED file, so it must NEVER carry a real
 * secret. A secret-named variable or a secret-looking value is blanked (the user fills it in); safe,
 * short config defaults (ports, NODE_ENV, plain URLs) are preserved as helpful hints.
 */
function safeExampleValue(key: string, val: string): string {
  if (!val) return '';
  if (SECRET_KEY_RE.test(key) || looksSecretValue(val)) return '';
  return val;
}

/**
 * Build a `.env.example` from the variable names the code references, merged with any existing file
 * (existing keys are kept even if no longer referenced, so nothing is silently dropped). Values are
 * emitted only when they are SAFE (secret-named vars and secret-looking values are blanked) because
 * `.env.example` is committed to version control. PURE & deterministic.
 */
export function generateEnvExample(refs: string[], existing?: string | null): string {
  const existingMap = parseExisting(existing);
  const keys = new Set<string>(existingMap.keys());
  for (const k of refs || []) {
    if (typeof k === 'string' && /^[A-Za-z_][A-Za-z0-9_]*$/.test(k)) keys.add(k);
  }
  const sorted = [...keys].sort();

  const lines: string[] = [
    '# Environment variables for this project.',
    '# Copy this file to .env and fill in the values.',
    '# Generated by NavBharatAI Pro v3.0 from the variables the code references.',
    '',
  ];
  for (const k of sorted) {
    lines.push(`${k}=${safeExampleValue(k, existingMap.get(k) ?? '')}`);
  }
  return lines.join('\n') + '\n';
}
