// AgentV3 — Config engine: .env.example generator (Phase 4 v1).
//
// The classic "your app won't run for anyone else" defect is a missing/incomplete
// `.env.example`: the code reads process.env.X / import.meta.env.X but nothing tells
// the next person which variables to set. `EnvVarAnalysis` already DETECTS this; this
// PURE function GENERATES the fix — a `.env.example` listing every variable the code
// actually references, preserving any values already documented. Derived entirely
// from real references — never invents variables.

/** Parse an existing .env/.env.example into KEY → value, ignoring comments/blanks. */
function parseExisting(raw?: string | null): Map<string, string> {
  const m = new Map<string, string>();
  if (!raw) return m;
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    const key = t.slice(0, eq).trim();
    const val = t.slice(eq + 1).trim();
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) m.set(key, val);
  }
  return m;
}

/**
 * Build a `.env.example` from the variable names the code references, merged with
 * any existing file (existing values are preserved; existing keys are kept even if
 * no longer referenced, so nothing is silently dropped). PURE & deterministic.
 */
export function generateEnvExample(refs: string[], existing?: string | null): string {
  const existingMap = parseExisting(existing);
  const keys = new Set<string>(existingMap.keys());
  for (const k of refs || []) {
    if (typeof k === 'string' && /^[A-Za-z_][A-Za-z0-9_]*$/.test(k)) keys.add(k);
  }
  const sorted = [...keys].sort();

  const lines: string[] = [
    '# Environment variables for this project.',
    '# Copy this file to .env and fill in the values.',
    '# Generated by NavBharatAI Pro v3.0 from the variables the code references.',
    '',
  ];
  for (const k of sorted) {
    const val = existingMap.get(k);
    lines.push(`${k}=${val ?? ''}`);
  }
  return lines.join('\n') + '\n';
}
