import { describe, it, expect } from 'vitest';
import { generateEnvExample } from './EnvExampleGenerator';

describe('generateEnvExample', () => {
  it('lists referenced variables, sorted, with empty placeholders', () => {
    const out = generateEnvExample(['STRIPE_KEY', 'API_URL', 'API_URL']);
    expect(out).toContain('# Generated by NavBharatAI Pro v3.0');
    // sorted: API_URL before STRIPE_KEY; deduped
    const body = out.split('\n').filter((l) => l && !l.startsWith('#'));
    expect(body).toEqual(['API_URL=', 'STRIPE_KEY=']);
  });

  it('preserves values already documented in the existing file', () => {
    const existing = '# comment\nAPI_URL=https://api.example.com\nUNUSED=keepme\n';
    const out = generateEnvExample(['API_URL', 'NEW_KEY'], existing);
    expect(out).toContain('API_URL=https://api.example.com');
    expect(out).toContain('NEW_KEY=');
    // existing key not referenced is kept, not dropped
    expect(out).toContain('UNUSED=keepme');
  });

  it('ignores invalid variable names', () => {
    const out = generateEnvExample(['GOOD_ONE', '123bad', 'has-dash', '']);
    expect(out).toContain('GOOD_ONE=');
    expect(out).not.toContain('123bad');
    expect(out).not.toContain('has-dash');
  });

  it('produces just the header when there is nothing to document', () => {
    const out = generateEnvExample([]);
    expect(out).toContain('# Environment variables for this project.');
    const body = out.split('\n').filter((l) => l && !l.startsWith('#'));
    expect(body).toEqual([]);
  });

  it('ends with a trailing newline', () => {
    expect(generateEnvExample(['X']).endsWith('\n')).toBe(true);
  });
});
