// AgentV3 — Config engine: .gitignore generator (Section I #22 v1).
//
// The project-hygiene check flags a missing .gitignore (without it node_modules,
// build output and .env secrets get committed). This PURE function GENERATES a
// correct, stack-aware .gitignore so the agent can fix that in one call. Framework
// entries are added from the project's real dependencies — nothing invented.

export interface GitignoreInput {
  /** Project dependency names (used to add framework-specific ignores). */
  dependencies?: string[];
}

const BASE: Array<[string, string[]]> = [
  ['Dependencies', ['node_modules/']],
  ['Build output', ['dist/', 'build/']],
  ['Environment & secrets', ['.env', '.env.local', '.env.*.local', '*.pem']],
  ['Logs', ['*.log', 'npm-debug.log*', 'yarn-debug.log*', 'pnpm-debug.log*']],
  ['Test coverage', ['coverage/']],
  ['Editor & OS', ['.DS_Store', '.vscode/', '.idea/', 'Thumbs.db']],
];

// dependency → extra ignore lines for that framework/tool.
const FRAMEWORK: Array<[RegExp, string[]]> = [
  [/^next$/, ['.next/', 'out/']],
  [/^nuxt$/, ['.nuxt/', '.output/']],
  [/^gatsby$/, ['.cache/', 'public/']],
  [/^@remix-run\//, ['.cache/', 'build/', 'public/build/']],
  [/^@sveltejs\/kit$/, ['.svelte-kit/']],
  [/^astro$/, ['.astro/']],
  [/^vite$/, ['*.local']],
];

/** Generate a stack-aware .gitignore. PURE & deterministic. */
export function generateGitignore(input: GitignoreInput = {}): string {
  const deps = Array.isArray(input.dependencies) ? input.dependencies : [];
  const seen = new Set<string>();
  const sections: string[] = ['# Generated by NavBharatAI Pro v3.0', ''];

  for (const [title, entries] of BASE) {
    const lines = entries.filter((e) => !seen.has(e));
    if (!lines.length) continue;
    lines.forEach((e) => seen.add(e));
    sections.push(`# ${title}`, ...lines, '');
  }

  const fw: string[] = [];
  for (const dep of deps) {
    for (const [re, entries] of FRAMEWORK) {
      if (re.test(dep)) {
        for (const e of entries) if (!seen.has(e)) { seen.add(e); fw.push(e); }
      }
    }
  }
  if (fw.length) sections.push('# Framework', ...fw, '');

  return sections.join('\n').replace(/\n+$/, '\n');
}
