import { describe, it, expect } from 'vitest';
import { generateGitignore } from './GitignoreGenerator';

describe('generateGitignore', () => {
  it('always includes the core ignores', () => {
    const g = generateGitignore();
    for (const e of ['node_modules/', 'dist/', '.env', '*.log', 'coverage/', '.DS_Store']) {
      expect(g).toContain(e);
    }
    expect(g).toContain('# Generated by NavBharatAI Pro v3.0');
  });

  it('adds framework entries from dependencies', () => {
    const g = generateGitignore({ dependencies: ['next', 'react'] });
    expect(g).toContain('.next/');
    expect(g).toContain('out/');
    expect(g).toContain('# Framework');
  });

  it('does not add framework entries for an unknown stack', () => {
    const g = generateGitignore({ dependencies: ['react', 'express'] });
    expect(g).not.toContain('# Framework');
  });

  it('does not duplicate an entry', () => {
    const g = generateGitignore({ dependencies: ['next'] });
    expect((g.match(/^node_modules\/$/gm) || []).length).toBe(1);
  });

  it('ends with a single trailing newline', () => {
    const g = generateGitignore();
    expect(g.endsWith('\n')).toBe(true);
    expect(g.endsWith('\n\n')).toBe(false);
  });
});
