import { describe, it, expect } from 'vitest';
import { generateReadme } from './ReadmeGenerator';
import type { ProjectGraph } from './WorkspaceMemory';

function graph(partial: Partial<ProjectGraph>): ProjectGraph {
  return {
    files: [],
    symbols: [],
    components: [],
    routes: [],
    imports: {},
    dependencies: [],
    ...partial,
  };
}

describe('generateReadme', () => {
  it('uses the package name/description and detects the stack from deps', () => {
    const pkg = JSON.stringify({
      name: 'todo-app',
      description: 'A simple todo list.',
      scripts: { dev: 'vite', build: 'vite build' },
      dependencies: { react: '^18', 'react-dom': '^18' },
      devDependencies: { vite: '^5', typescript: '^5', tailwindcss: '^3' },
    });
    const md = generateReadme({ graph: graph({ components: ['TodoList'] }), packageJson: pkg });

    expect(md).toContain('# todo-app');
    expect(md).toContain('A simple todo list.');
    expect(md).toContain('- React');
    expect(md).toContain('- Vite');
    expect(md).toContain('- TypeScript');
    expect(md).toContain('- Tailwind CSS');
    // React must not be duplicated even though react + react-dom both map to it.
    expect(md.match(/- React$/gm) || []).toHaveLength(1);
  });

  it('prefers a real dev script for the run command', () => {
    const pkg = JSON.stringify({ scripts: { dev: 'vite' } });
    expect(generateReadme({ graph: graph({}), packageJson: pkg })).toContain('npm run dev');

    const pkg2 = JSON.stringify({ scripts: { start: 'node server.js' } });
    expect(generateReadme({ graph: graph({}), packageJson: pkg2 })).toContain('npm start');
  });

  it('summarizes components and routes from the graph', () => {
    const md = generateReadme({
      graph: graph({
        files: ['src/A.tsx', 'src/B.tsx'],
        components: ['Header', 'Footer'],
        routes: ['/', '/about'],
      }),
    });
    expect(md).toContain('2 file(s), 2 component(s), 2 route(s)');
    expect(md).toContain('Header, Footer');
    expect(md).toContain('/about');
  });

  it('lists available scripts when present', () => {
    const pkg = JSON.stringify({ scripts: { dev: 'vite', test: 'vitest' } });
    const md = generateReadme({ graph: graph({}), packageJson: pkg });
    expect(md).toContain('## Available Scripts');
    expect(md).toContain('`npm run test`');
  });

  it('produces an honest minimal README with no package.json', () => {
    const md = generateReadme({ projectName: 'Bare', graph: graph({}) });
    expect(md).toContain('# Bare');
    expect(md).toContain('(not detected yet)');
    expect(md).toContain('npm install');
    expect(md).toContain('_Generated by NavBharatAI Pro v3.0._');
  });

  it('survives malformed package.json', () => {
    const md = generateReadme({ graph: graph({ components: ['X'] }), packageJson: '{ not json' });
    expect(md).toContain('# My App');
    expect(md).toContain('1 component(s)');
  });
});
