import { IGenerationEngine, Patch } from './IGenerationEngine';
import { GenerationTask } from './PlannerTypes';

export class DefaultGenerationEngine implements IGenerationEngine {
    async execute(task: GenerationTask): Promise<Patch[]> {
        // Implementation for Default generation
        // Simulating logic based on task requirements
        return [
            {
                path: 'README.md',
                content: '# Generated Project\n\nThis project was generated by DefaultGenerationEngine.'
            }
        ];
    }
}
