import OpenAI from 'openai';
import { getGemini, getGroq, getDeepSeek, getOpenAI, getOpenRouter, getClaude, resolveApiKey } from './aiClients';
import { getBharatContext } from './prompts';

/**
 * Provider-specific AI call functions, extracted from the server.ts monolith
 * (Phase 1, AI-core step b). Each resolves a client via aiClients and returns
 * the assistant text. Behavior unchanged.
 */

export async function callGemini(message: string, key?: string, history: any[] = [], systemInstruction?: string): Promise<string> {
  const ai = getGemini(key);

  if (!ai) {
    throw new Error(`Gemini API Key missing or invalid! Please ensure a valid key is set in Settings.`);
  }

  const modelCandidate = 'gemini-3.5-flash'; // Primary active model based on guidelines

  try {
    const contents = history.map(msg => ({
      role: msg.sender === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));

    contents.push({ role: 'user', parts: [{ text: message }] });

    const result = await ai.models.generateContent({
      model: modelCandidate,
      contents: contents,
      config: {
        systemInstruction: systemInstruction || getBharatContext(),
        tools: [{ googleSearch: {} }]
      }
    });

    // Handle the response structure of @google/genai SDK
    const reply = result.candidates?.[0]?.content?.parts?.[0]?.text || (result as any).text || (result as any).response?.text?.();
    if (!reply) throw new Error('No content generated by AI');
    return reply;
  } catch (e: any) {
    console.error(`[API] Gemini call failed:`, e.reason || e.message);
    throw e;
  }
}

export async function callGroq(message: string, key?: string, history: any[] = []): Promise<string> {
  const client = getGroq(key);
  if (!client) throw new Error('Groq API Key not available');

  const messages: any[] = [
    { role: 'system', content: getBharatContext() },
    ...history.map(m => ({ role: m.sender === 'user' ? 'user' : 'assistant', content: m.text })),
    { role: 'user', content: message }
  ];

  const completion = await client.chat.completions.create({
    messages,
    model: 'mixtral-8x7b-32768',
  });
  return completion.choices[0]?.message?.content ?? 'Groq error';
}

export async function callDeepSeek(message: string, key?: string, history: any[] = []): Promise<string> {
  const client = getDeepSeek(key) || getOpenRouter(key);
  if (!client) throw new Error('DeepSeek/OpenRouter API Key not available');

  const model = client.baseURL.includes('openrouter') ? 'deepseek/deepseek-chat' : 'deepseek-chat';
  const messages: any[] = [
    { role: 'system', content: getBharatContext() + " You are an expert programmer." },
    ...history.map(m => ({ role: m.sender === 'user' ? 'user' : 'assistant', content: m.text })),
    { role: 'user', content: message }
  ];

  const completion = await client.chat.completions.create({
    messages,
    model,
  });
  return completion.choices[0]?.message?.content ?? 'DeepSeek error';
}

export async function callOpenAI(message: string, key?: string, history: any[] = []): Promise<string> {
  const client = getOpenAI(key);
  if (!client) throw new Error('OpenAI API Key not available');

  const messages: any[] = [
    { role: 'system', content: getBharatContext() },
    ...history.map(m => ({ role: m.sender === 'user' ? 'user' : 'assistant', content: m.text })),
    { role: 'user', content: message }
  ];

  const completion = await client.chat.completions.create({
    messages,
    model: 'gpt-4o-mini',
  });
  return completion.choices[0]?.message?.content ?? 'OpenAI error';
}

export async function callClaude(message: string, key?: string, history: any[] = [], systemInstruction?: string): Promise<string> {
  const { key: resolvedKey, source } = resolveApiKey('claude', key);
  if (!resolvedKey) {
    throw new Error('Claude API Key not available');
  }

  // Support for OpenAI compatible proxy (e.g. aicredits.in) when ANTHROPIC_BASE_URL is configured
  if (process.env.ANTHROPIC_BASE_URL) {
    console.log(`[AUTH] Claude routing via OpenAI proxy: ${process.env.ANTHROPIC_BASE_URL} (source: ${source})`);
    const client = new OpenAI({
      apiKey: resolvedKey,
      baseURL: process.env.ANTHROPIC_BASE_URL
    });
    // Try standard proxy/gateway compatible model names (including verified aicredits active mappings)
    const modelsToTry = [
      'anthropic/claude-sonnet-4.6',
      'anthropic/claude-sonnet-4',
      'claude-sonnet-4-6',
      'anthropic/claude-opus-4.7-fast',
      'anthropic/claude-opus-4.7',
      'anthropic/claude-3-haiku',
      'claude-3-5-sonnet-latest',
      'claude-3-5-sonnet',
      'claude-3.5-sonnet',
      'anthropic/claude-3.5-sonnet',
      'claude-3-5-sonnet-20241022',
      'anthropic/claude-3-5-sonnet-latest',
      'claude-3-opus'
    ];

    let lastErr = null;
    for (const modelName of modelsToTry) {
      try {
        console.log(`[AUTH] Calling Claude proxy model: ${modelName}`);
        const completion = await client.chat.completions.create({
          model: modelName,
          messages: [
            ...(systemInstruction ? [{ role: 'system' as const, content: systemInstruction }] : [{ role: 'system' as const, content: getBharatContext() }]),
            ...history.map(m => ({
              role: (m.sender === 'user' ? 'user' : 'assistant') as 'user' | 'assistant',
              content: m.text as string
            })),
            { role: 'user' as const, content: message }
          ]
        });
        const ans = completion.choices[0]?.message?.content;
        if (ans) return ans;
      } catch (err: any) {
        console.warn(`[AUTH] Claude proxy failed with model ${modelName}: ${err.message}`);
        lastErr = err;
      }
    }
    throw lastErr || new Error('Claude proxy failed');
  }

  // Normal Anthropic SDK usage (e.g. for User supplied keys with no custom base URL)
  const client = getClaude(key);
  if (!client) throw new Error('Claude API Key not available');

  const messages: any[] = history.map(m => ({
    role: m.sender === 'user' ? 'user' : 'assistant' as const,
    content: m.text
  }));
  messages.push({ role: 'user', content: message });

  const response = await client.messages.create({
    model: "claude-3-5-sonnet-20241022",
    max_tokens: 4096,
    system: systemInstruction || getBharatContext(),
    messages,
  });
  return response.content[0].type === 'text' ? response.content[0].text : 'Claude error';
}

export async function callOpenRouter(message: string, key?: string, history: any[] = []): Promise<string> {
  const client = getOpenRouter(key);
  if (!client) throw new Error('OpenRouter API Key not available');

  const messages: any[] = [
    { role: 'system', content: getBharatContext() },
    ...history.map(m => ({ role: m.sender === 'user' ? 'user' : 'assistant', content: m.text })),
    { role: 'user', content: message }
  ];

  const completion = await client.chat.completions.create({
    messages,
    model: 'deepseek/deepseek-chat',
  });
  return completion.choices[0]?.message?.content ?? 'OpenRouter error';
}
