import { getGemini, getGroq, getClaude, resolveApiKey } from './aiClients';
import { getBharatContext } from './prompts';

export async function callGemini(message: string, key?: string, history: any[] = [], systemInstruction?: string): Promise<string> {
  const ai = getGemini(key);

  if (!ai) {
    throw new Error(`Gemini API Key missing or invalid! Please ensure a valid key is set in Settings.`);
  }

  const modelCandidate = 'gemini-2.5-flash';

  try {
    const contents = history.map(msg => ({
      role: msg.sender === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));

    contents.push({ role: 'user', parts: [{ text: message }] });

    const result = await ai.models.generateContent({
      model: modelCandidate,
      contents: contents,
      config: {
        systemInstruction: systemInstruction || getBharatContext(),
        tools: [{ googleSearch: {} }],
        // Generous output budget so multi-file code edits aren't truncated
        // mid-JSON (a truncated reply parses to ZERO file edits → the edit
        // silently no-ops, which is why editing died after a few rounds).
        maxOutputTokens: 16000,
      }
    });

    // Handle the response structure of @google/genai SDK
    const reply = result.candidates?.[0]?.content?.parts?.[0]?.text || (result as any).text || (result as any).response?.text?.();
    if (!reply) throw new Error('No content generated by AI');
    return reply;
  } catch (e: any) {
    console.error(`[API] Gemini call failed:`, e.reason || e.message);
    throw e;
  }
}

export async function callGroq(message: string, key?: string, history: any[] = []): Promise<string> {
  const client = getGroq(key);
  if (!client) throw new Error('Groq API Key not available');

  const messages: any[] = [
    { role: 'system', content: getBharatContext() },
    ...history.map(m => ({ role: m.sender === 'user' ? 'user' : 'assistant', content: m.text })),
    { role: 'user', content: message }
  ];

  const completion = await client.chat.completions.create({
    messages,
    model: 'mixtral-8x7b-32768',
    max_tokens: 8000,   // avoid truncating multi-file code edits mid-JSON
  });
  return completion.choices[0]?.message?.content ?? 'Groq error';
}

export async function callClaude(message: string, key?: string, history: any[] = [], systemInstruction?: string): Promise<string> {
  const { key: resolvedKey } = resolveApiKey('claude', key);
  if (!resolvedKey) {
    throw new Error('Claude API Key not available');
  }

  // Native Anthropic SDK (direct to api.anthropic.com). The OpenAI-compatible
  // aicredits proxy has been removed — Claude is called natively only.
  const client = getClaude(key);
  if (!client) throw new Error('Claude API Key not available');

  const messages: any[] = history.map(m => ({
    role: m.sender === 'user' ? 'user' : 'assistant' as const,
    content: m.text
  }));
  messages.push({ role: 'user', content: message });

  const response = await client.messages.create({
    // claude-3-5-sonnet-20241022 is retired (404s) — keep this on a current model.
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    system: systemInstruction || getBharatContext(),
    messages,
  });
  return response.content[0].type === 'text' ? response.content[0].text : 'Claude error';
}

