// REAL code minification — ROOT-CAUSE FIX (admin 2026-07-26, while wiring the Minifier to users' own
// app files).
//
// WHAT WAS THERE: the Minifier minified JavaScript with hand-written regexes in the browser. Those
// regexes are not merely imprecise, they reliably emit BROKEN JavaScript on ordinary input. Measured,
// not guessed:
//
//   const api = "https://navbharatai.com/api";   →  const api="https:        (SyntaxError)
//   console.log(getName(user)); render();        →  );render();              (SyntaxError)
//   `line1\nline2`                               →  `line1 line2`            (silently altered text)
//
// The first case alone means every app v5 builds gets corrupted, because every app has an API URL:
// `//` inside a string literal is indistinguishable from a comment to a regex. The second breaks on
// any nested call. The third rewrites the user's own text inside template literals.
//
// This was survivable only while the tool was paste-in/paste-out and a human eyeballed the result. The
// moment "Apply" writes back into a real project file, the same code silently destroys users' apps —
// which the first absolute rule forbids outright.
//
// THE FIX: minify with esbuild, the same engine Vite already uses to build this very app. It parses the
// code into a real AST, so a string containing "//" stays a string and nested calls stay balanced. It
// also FAILS LOUDLY on input it cannot parse, which is what lets us promise never to hand back output
// that is more broken than the input.
//
// Everything here is I/O-free apart from esbuild itself and is unit-tested against the exact cases the
// regex version got wrong.

export type MinifyLanguage = 'js' | 'ts' | 'jsx' | 'tsx' | 'css' | 'html' | 'json';

export interface MinifyResult {
  ok: boolean;
  /** Minified source. Only meaningful when ok — never a partially-mangled fallback. */
  code: string;
  originalBytes: number;
  minifiedBytes: number;
  /** Bytes saved; 0 when minification could not help (or failed). */
  savedBytes: number;
  /** 0–100. */
  savedPercent: number;
  /** Present only when ok === false — the real parser error, never a vague "something went wrong". */
  error?: string;
  /** Language actually used (after detection, when the caller did not specify one). */
  language: MinifyLanguage;
}

/** Map a filename to the loader esbuild should use. Pure. */
export function detectLanguage(filename: string): MinifyLanguage {
  const ext = (filename.split('.').pop() || '').toLowerCase();
  switch (ext) {
    case 'ts': return 'ts';
    case 'tsx': return 'tsx';
    case 'jsx': return 'jsx';
    case 'css': return 'css';
    case 'html': case 'htm': return 'html';
    case 'json': return 'json';
    default: return 'js';
  }
}

/**
 * Files that must NEVER be minified, because doing so is either destructive or pointless.
 *
 * This is a real guard, not tidiness: minifying a lockfile or a config the toolchain parses by hand
 * can break the project, and minifying an already-minified bundle just wastes a round-trip.
 */
export function isMinifiable(filename: string): boolean {
  const f = filename.toLowerCase();
  if (/\.min\.(js|css)$/.test(f)) return false;              // already minified
  if (/(^|\/)package-lock\.json$/.test(f)) return false;      // regenerated by npm; never hand-edit
  if (/(^|\/)(package\.json|tsconfig[^/]*\.json)$/.test(f)) return false; // toolchain reads these
  if (/\.(md|txt|svg|png|jpe?g|gif|webp|ico|lock|ya?ml|toml)$/.test(f)) return false;
  return /\.(js|jsx|ts|tsx|css|html?|json)$/.test(f);
}

function pct(original: number, minified: number): number {
  if (original <= 0) return 0;
  return Math.max(0, Math.round(((original - minified) / original) * 1000) / 10);
}

/**
 * Minify one file's source with esbuild.
 *
 * Guarantees, in order of importance:
 *  1. NEVER returns mangled output. If esbuild cannot parse the input, ok is false, the ORIGINAL code
 *     comes back untouched, and the parser's real message is reported.
 *  2. NEVER returns output larger than the input — if minifying somehow grows the file, the original is
 *     kept and savedBytes is 0. A "minifier" that inflates a file has failed at its one job.
 */
export async function minifySource(
  code: string,
  filenameOrLanguage: string,
  opts: { keepConsole?: boolean } = {},
): Promise<MinifyResult> {
  const language: MinifyLanguage = (['js', 'ts', 'jsx', 'tsx', 'css', 'html', 'json'] as const)
    .includes(filenameOrLanguage as MinifyLanguage)
    ? (filenameOrLanguage as MinifyLanguage)
    : detectLanguage(filenameOrLanguage);

  const originalBytes = Buffer.byteLength(code, 'utf8');
  const fail = (error: string): MinifyResult => ({
    ok: false, code, originalBytes, minifiedBytes: originalBytes,
    savedBytes: 0, savedPercent: 0, error, language,
  });

  // esbuild has no HTML loader. Rather than fall back to the regex approach that caused this whole
  // problem, we decline honestly — a half-safe HTML minifier is how the original bug shipped.
  if (language === 'html') {
    return fail('HTML minification is not supported yet. The production build already minifies the JS and CSS this page loads.');
  }

  try {
    const esbuild = await import('esbuild');
    const result = await esbuild.transform(code, {
      loader: language === 'json' ? 'json' : language,
      minify: true,
      // Dropping console/debugger is a real pre-ship win, but it changes behaviour, so it is opt-out
      // rather than silent. esbuild removes them at the AST level — no dangling parens.
      drop: opts.keepConsole ? [] : ['console', 'debugger'],
      legalComments: 'none',
    });

    const minifiedBytes = Buffer.byteLength(result.code, 'utf8');
    // Tiny inputs can come out LARGER once minified (esbuild may add a trailing newline or semicolon).
    // Handing back a bigger file while claiming to have shrunk it would be a lie.
    if (minifiedBytes >= originalBytes) {
      return {
        ok: true, code, originalBytes, minifiedBytes: originalBytes,
        savedBytes: 0, savedPercent: 0, language,
      };
    }

    return {
      ok: true,
      code: result.code,
      originalBytes,
      minifiedBytes,
      savedBytes: originalBytes - minifiedBytes,
      savedPercent: pct(originalBytes, minifiedBytes),
      language,
    };
  } catch (e) {
    // esbuild throws with the line/column of the real syntax problem — pass it through verbatim so the
    // user can fix their code, instead of silently shipping something broken.
    const msg = (e as { message?: string })?.message || String(e);
    return fail(msg);
  }
}
