// UT-1 (desktop output) — Electron desktop-export generator for a USER's generated web app.
//
// Turns a generated web app (it builds to a static `webDir`) into a desktop app by emitting an Electron
// wrapper: an `electron/main.cjs` that loads the built HTML in a BrowserWindow, an `electron-builder.yml`
// targeting Windows (.exe/NSIS), macOS (.dmg) and Linux (.AppImage), and a `DESKTOP_EXPORT.md` runbook.
//
// HONESTY (rule 6 — what this does NOT do): it generates the wrapper CONFIG, not the packaged binary. A real
// signed `.exe` needs a Windows runner (NSIS), a signed `.dmg` needs macOS + an Apple identity — the Linux
// sandbox / an in-process generator cannot produce them. The runbook states this and gives the runner steps.
//
// PURE + deterministic; unit-tested. Emits a `files` map + `dependencies` in the recipe-generator shape so the
// ToolDispatcher reuses the same write loop and never clobbers an existing electron-builder.yml.

import { resolveAppId } from './appId';

export interface DesktopExportOptions {
  /** Human product name shown on the app/window (e.g. "My Shop"). */
  appName?: string;
  /** Reverse-DNS application id (e.g. com.acme.myshop). Derived from appName when omitted/invalid. */
  appId?: string;
  /** The build output directory Electron loads (Vite → 'dist', CRA → 'build', Next export → 'out'). */
  webDir?: string;
}

export interface DesktopExportResult {
  files: Record<string, string>;
  /** Electron packages to add (devDependencies). */
  dependencies: Array<{ name: string; version: string }>;
  /** package.json scripts the user should add to run/package the desktop app. */
  scripts: Record<string, string>;
  /** The package.json "main" entry Electron needs. */
  mainEntry: string;
  appId: string;
  instructions: string;
}

const clean = (s: unknown): string => (typeof s === 'string' ? s.trim() : '');

const MAIN_CJS = (webDir: string): string => `// Generated by NavBharatAI (desktop export). Electron main process — loads the built web app.
const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    webPreferences: { contextIsolation: true },
  });
  // Load the built web app. Run your web build (produces ${webDir}/) BEFORE packaging.
  win.loadFile(path.join(__dirname, '..', ${JSON.stringify(webDir)}, 'index.html'));
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  // On macOS apps stay active until the user quits explicitly.
  if (process.platform !== 'darwin') app.quit();
});
`;

const BUILDER_YML = (appId: string, appName: string, webDir: string): string => `# Generated by NavBharatAI (desktop export). electron-builder configuration.
appId: ${appId}
productName: ${JSON.stringify(appName)}
directories:
  output: release
files:
  - ${webDir}/**/*
  - electron/**/*
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
`;

const README = (appId: string, webDir: string): string => `# Desktop export (Electron)

This project can ship as a desktop app (Windows/.exe, macOS/.dmg, Linux/.AppImage). NavBharatAI generated the
Electron wrapper: \`electron/main.cjs\` loads your built web app (\`${webDir}/\`) and \`electron-builder.yml\`
packages it (app id \`${appId}\`).

## One-time setup
1. Add the reported devDependencies + scripts to \`package.json\`, and set \`"main": "electron/main.cjs"\`.
2. \`npm install\`
3. **Important for a file:// build:** set your bundler's base path to relative so assets resolve when loaded
   from disk — Vite: \`base: './'\` in \`vite.config\`; CRA: \`"homepage": "."\` in package.json. Without this the
   packaged window loads blank (absolute \`/assets/...\` paths 404 under file://).

## Run / package
1. \`npm run build\`          — build the web assets into \`${webDir}/\`
2. \`npm run electron:start\` — run the app locally in an Electron window
3. \`npm run electron:build\` — package installers into \`release/\`

## Producing the installers (needs the target OS — NOT done here)
electron-builder builds **for the OS it runs on**: a real \`.exe\` (NSIS) needs a **Windows** runner, a signed
\`.dmg\` needs **macOS** + an Apple signing identity; only \`.AppImage\` builds on Linux. NavBharatAI generates
the wrapper, not the signed installer — run \`npm run electron:build\` on the matching OS / CI runner. Never
commit signing certificates.
`;

/**
 * Generate an Electron desktop-export wrapper for a generated web app. Deterministic; pure.
 * The `webDir` defaults to 'dist' (Vite). Caller passes the real build dir when known.
 */
export function generateDesktopExport(opts: DesktopExportOptions = {}): DesktopExportResult {
  const appName = clean(opts.appName) || 'My App';
  const appId = resolveAppId(opts.appId, appName);
  const webDir = clean(opts.webDir) || 'dist';

  const scripts: Record<string, string> = {
    'electron:start': 'electron .',
    'electron:build': 'electron-builder',
  };

  return {
    appId,
    mainEntry: 'electron/main.cjs',
    dependencies: [
      { name: 'electron', version: '^31' },
      { name: 'electron-builder', version: '^25' },
    ],
    scripts,
    files: {
      'electron/main.cjs': MAIN_CJS(webDir),
      'electron-builder.yml': BUILDER_YML(appId, appName, webDir),
      'DESKTOP_EXPORT.md': README(appId, webDir),
    },
    instructions: `Wrapped this app as an Electron desktop project (appId ${appId}, webDir ${webDir}). Add the devDependencies + the scripts (${Object.keys(scripts).join(', ')}) to package.json and set "main": "electron/main.cjs". Also set a RELATIVE base path (Vite base: './') so assets load under file://. Then: npm install → npm run build → npm run electron:start. Signed installers (.exe/.dmg) are NOT produced here — electron-builder must run on the matching OS/runner (see DESKTOP_EXPORT.md).`,
  };
}
