import { describe, it, expect } from 'vitest';
import { generateReadme, generateApiDocs, generateTsDoc, generateDocs } from './DocGenerator';

describe('DocGenerator (P-CGE.2)', () => {
  describe('generateReadme', () => {
    it('builds a README from a full blueprint', () => {
      const md = generateReadme({
        name: 'TodoApp',
        description: 'A simple todo manager.',
        features: ['Login', 'Tasks'],
        techStack: ['React', 'Firebase'],
        setup: { install: 'npm install', run: 'npm run dev', env: ['API_KEY'] },
      });
      expect(md).toContain('# TodoApp');
      expect(md).toContain('A simple todo manager.');
      expect(md).toContain('## Features');
      expect(md).toContain('- Login');
      expect(md).toContain('React · Firebase');
      expect(md).toContain('## Getting Started');
      expect(md).toContain('`API_KEY`');
      expect(md).toContain('npm install');
      expect(md).toContain('npm run dev');
      expect(md).toContain('_Generated by NavBharatAI._');
    });

    it('HONESTY: an empty blueprint yields a minimal README, no fabricated sections', () => {
      const md = generateReadme({});
      expect(md).toContain('# App');
      expect(md).not.toContain('## Features');
      expect(md).not.toContain('## Getting Started');
    });
  });

  describe('generateApiDocs', () => {
    it('builds a sorted route table', () => {
      const md = generateApiDocs([
        { method: 'post', path: '/api/users', description: 'Create a user', auth: true },
        { method: 'get', path: '/api/health' },
      ]);
      expect(md).toContain('# API Reference');
      expect(md).toContain('| GET | `/api/health` | — | — |');
      expect(md).toContain('| POST | `/api/users` | 🔒 | Create a user |');
      // /api/health sorts before /api/users
      expect(md.indexOf('/api/health')).toBeLessThan(md.indexOf('/api/users'));
    });
    it('honestly reports no routes', () => {
      expect(generateApiDocs([])).toContain('_No routes documented._');
    });
    it('escapes a pipe and collapses newlines in a description so the table is not corrupted', () => {
      const md = generateApiDocs([
        { method: 'get', path: '/x', description: 'Returns a | b\nsecond line' },
      ]);
      const row = md.split('\n').find((l) => l.startsWith('| GET'))!;
      // exactly 5 pipes delimiting 4 cells — an unescaped `|`/newline would add columns or split the row.
      expect((row.match(/(?<!\\)\|/g) || []).length).toBe(5);
      expect(row).toContain('Returns a \\| b second line');
    });
  });

  describe('generateTsDoc', () => {
    it('builds a TSDoc block with params and returns', () => {
      const doc = generateTsDoc({
        name: 'add', description: 'Adds two numbers.',
        params: [{ name: 'a', type: 'number' }, { name: 'b', type: 'number' }],
        returns: 'number',
      });
      expect(doc).toContain('/**');
      expect(doc).toContain(' * Adds two numbers.');
      expect(doc).toContain(' * @param a - {number}');
      expect(doc).toContain(' * @returns {number}');
      expect(doc.trim().endsWith('*/')).toBe(true);
    });
    it('falls back to the function name when no description is given', () => {
      expect(generateTsDoc({ name: 'doThing' })).toContain(' * doThing.');
    });
  });

  describe('generateDocs', () => {
    it('returns only the docs the input supports', () => {
      const out = generateDocs({ blueprint: { name: 'X' }, routes: [{ method: 'get', path: '/a' }] });
      expect(out.readme).toBeTruthy();
      expect(out.apiDocs).toBeTruthy();
      expect(out.tsdoc).toBeUndefined();
    });
  });
});
