// P-CGE.2 — Documentation Generators.
//
// Pure, dependency-free generators that turn an app blueprint into documentation:
//   • generateReadme   — README.md from name/description/features/tech-stack/setup
//   • generateApiDocs  — an API reference from a list of routes
//   • generateTsDoc    — a TSDoc comment block from a parsed function signature
//
// HONESTY: every line is derived from the supplied input. Sections with no data are omitted —
// an empty blueprint produces a minimal honest README, never invented features or fake setup steps.

export interface DocBlueprint {
  name?: string;
  description?: string;
  features?: string[];
  techStack?: string[];
  setup?: {
    install?: string;
    run?: string;
    env?: string[];
  };
}

const clean = (s: unknown): string => (typeof s === 'string' ? s.trim() : '');
const list = (xs: unknown): string[] => (Array.isArray(xs) ? xs.map(clean).filter(Boolean) : []);

/** Generate a README.md from an app blueprint. Pure. */
export function generateReadme(bp: DocBlueprint): string {
  const name = clean(bp.name) || 'App';
  const lines: string[] = [`# ${name}`, ''];

  const desc = clean(bp.description);
  if (desc) { lines.push(desc, ''); }

  const features = list(bp.features);
  if (features.length) {
    lines.push('## Features', '');
    for (const f of features) lines.push(`- ${f}`);
    lines.push('');
  }

  const stack = list(bp.techStack);
  if (stack.length) {
    lines.push('## Tech Stack', '');
    lines.push(stack.join(' · '), '');
  }

  const install = clean(bp.setup?.install);
  const run = clean(bp.setup?.run);
  const env = list(bp.setup?.env);
  if (install || run || env.length) {
    lines.push('## Getting Started', '');
    if (env.length) {
      lines.push('Set these environment variables:', '');
      for (const e of env) lines.push(`- \`${e}\``);
      lines.push('');
    }
    if (install) { lines.push('```bash', install, '```', ''); }
    if (run) { lines.push('Run it:', '', '```bash', run, '```', ''); }
  }

  lines.push('---', '_Generated by NavBharatAI._');
  return lines.join('\n');
}

export interface RouteDoc {
  method: string;
  path: string;
  description?: string;
  auth?: boolean;
}

/** Generate an API reference (Markdown) from a list of routes. Pure. */
export function generateApiDocs(routes: RouteDoc[]): string {
  const valid = (routes || []).filter((r) => r && clean(r.method) && clean(r.path));
  if (valid.length === 0) return '# API Reference\n\n_No routes documented._';
  const lines: string[] = ['# API Reference', '', '| Method | Path | Auth | Description |', '| --- | --- | --- | --- |'];
  const sorted = [...valid].sort((a, b) => clean(a.path).localeCompare(clean(b.path)) || clean(a.method).localeCompare(clean(b.method)));
  for (const r of sorted) {
    const method = clean(r.method).toUpperCase();
    const auth = r.auth ? '🔒' : '—';
    const desc = clean(r.description) || '—';
    lines.push(`| ${method} | \`${clean(r.path)}\` | ${auth} | ${desc} |`);
  }
  return lines.join('\n');
}

export interface FunctionSignature {
  name: string;
  params?: Array<{ name: string; type?: string }>;
  returns?: string;
  description?: string;
}

/** Generate a TSDoc comment block from a parsed function signature. Pure. */
export function generateTsDoc(sig: FunctionSignature): string {
  const lines: string[] = ['/**'];
  const desc = clean(sig.description) || `${clean(sig.name) || 'function'}.`;
  lines.push(` * ${desc}`);
  const params = (sig.params || []).filter((p) => clean(p.name));
  if (params.length || clean(sig.returns)) lines.push(' *');
  for (const p of params) {
    const type = clean(p.type);
    lines.push(` * @param ${clean(p.name)}${type ? ` - {${type}}` : ''}`);
  }
  const ret = clean(sig.returns);
  if (ret) lines.push(` * @returns {${ret}}`);
  lines.push(' */');
  return lines.join('\n');
}

export interface DocBundle {
  readme?: string;
  apiDocs?: string;
  tsdoc?: string[];
}

/** Generate whatever docs the input supports (README / API / TSDoc blocks). Pure. */
export function generateDocs(input: { blueprint?: DocBlueprint; routes?: RouteDoc[]; signatures?: FunctionSignature[] }): DocBundle {
  const out: DocBundle = {};
  if (input.blueprint) out.readme = generateReadme(input.blueprint);
  if (input.routes && input.routes.length) out.apiDocs = generateApiDocs(input.routes);
  if (input.signatures && input.signatures.length) out.tsdoc = input.signatures.map(generateTsDoc);
  return out;
}
