// UT-2 (mobile output) — Capacitor mobile-export generator for a USER's generated web app.
//
// Turns a generated web app (Vite/Next/etc. — it builds to a static `webDir`) into a native mobile project
// by emitting a per-project Capacitor wrapper: a parameterized `capacitor.config.ts`, the package.json
// scripts + dependencies, and a `MOBILE_EXPORT.md` runbook. Capacitor is chosen because it wraps the app the
// user already built (no rewrite), and the platform itself already ships on Play/App Store this exact way.
//
// HONESTY (rule 6 — what this does NOT do): it generates the wrapper CONFIG, not a signed binary. Producing a
// real `.apk`/`.aab`/`.ipa` needs the Android SDK + Gradle (or macOS + Xcode) on a build runner and the user's
// own signing keystore — that is a runner/secrets task, not something an in-process generator or a Linux
// sandbox can do. The generated MOBILE_EXPORT.md states this plainly and gives the exact runner steps.
//
// PURE + deterministic (no I/O), unit-tested. Emits a `files` map + `dependencies` array in the same shape as
// the recipe generators so the ToolDispatcher reuses the same write loop and never clobbers an existing config.

export interface MobileExportOptions {
  /** Human app name shown on the device (e.g. "My Shop"). */
  appName?: string;
  /** Reverse-DNS application id (e.g. com.acme.myshop). Derived from appName when omitted/invalid. */
  appId?: string;
  /** The build output directory Capacitor packages (Vite → 'dist', CRA → 'build', Next export → 'out'). */
  webDir?: string;
}

export interface MobileExportResult {
  files: Record<string, string>;
  /** Capacitor packages to add (the wrapper needs these to sync/build the native project). */
  dependencies: Array<{ name: string; version: string }>;
  /** package.json scripts the user should add to drive Capacitor. */
  scripts: Record<string, string>;
  appId: string;
  instructions: string;
}

import { resolveAppId } from './appId';
import { DEFAULT_CAPACITOR_MAJOR } from './capacitorToolchain';
// Re-exported so existing importers keep a stable surface; the canonical impl lives in appId.ts (shared with
// the desktop generator — rule 4, no drift).
export { isValidAppId, deriveAppId } from './appId';

const clean = (s: unknown): string => (typeof s === 'string' ? s.trim() : '');

const CAP_CONFIG = (appId: string, appName: string, webDir: string): string => `import type { CapacitorConfig } from '@capacitor/cli';

// Generated by NavBharatAI (mobile export). Wraps this web app as a native mobile app via Capacitor.
const config: CapacitorConfig = {
  appId: ${JSON.stringify(appId)},
  appName: ${JSON.stringify(appName)},
  // The build output Capacitor packages into the native app. Run your web build before \`cap sync\`.
  webDir: ${JSON.stringify(webDir)},
};

export default config;
`;

const README = (appId: string, webDir: string, buildHint: string): string => `# Mobile export (Capacitor)

This project can ship as a native Android/iOS app. NavBharatAI generated the Capacitor **wrapper config**
(\`capacitor.config.ts\`) that packages your built web app (\`${webDir}/\`) as a native app id \`${appId}\`.

## One-time setup
1. Add the dependencies + scripts reported by the tool to \`package.json\`.
2. \`npm install\`
3. Build your web app: \`${buildHint}\` (produces \`${webDir}/\`).
4. Add the Android platform: \`npx cap add android\` (and \`npx cap add ios\` on a Mac).

## Each release
1. \`${buildHint}\`  — rebuild the web assets
2. \`npx cap sync\`  — copy them into the native project
3. Open the native IDE: \`npx cap open android\` (Android Studio) / \`npx cap open ios\` (Xcode)

## Producing the installable binary (needs a build runner — NOT done here)
A signed **.apk/.aab** (Android) needs the Android SDK + Gradle and **your own signing keystore**; an **.ipa**
(iOS) needs macOS + Xcode + an Apple signing identity. NavBharatAI generates the wrapper, not the signed
binary — run \`./gradlew bundleRelease\` (Android) or Xcode Archive (iOS) on a machine/CI runner that has the
native toolchain and your keystore. Never commit the keystore.
`;

/**
 * Generate a Capacitor mobile-export wrapper for a generated web app. Deterministic; pure.
 * The `webDir` defaults to 'dist' (Vite). Caller passes the real build dir when known.
 */
export function generateMobileExport(opts: MobileExportOptions = {}): MobileExportResult {
  const appName = clean(opts.appName) || 'My App';
  const appId = resolveAppId(opts.appId, appName);
  const webDir = clean(opts.webDir) || 'dist';
  const buildHint = 'npm run build';

  const scripts: Record<string, string> = {
    'cap:sync': 'cap sync',
    'cap:add:android': 'cap add android',
    'cap:open:android': 'cap open android',
  };

  return {
    appId,
    // The three Capacitor packages are one product and MUST share a major; the default comes from the
    // governed toolchain table so it can never drift from the Java the workflow pins (G2, 2026-08-11).
    dependencies: [
      { name: '@capacitor/core', version: `^${DEFAULT_CAPACITOR_MAJOR}` },
      { name: '@capacitor/cli', version: `^${DEFAULT_CAPACITOR_MAJOR}` },
      { name: '@capacitor/android', version: `^${DEFAULT_CAPACITOR_MAJOR}` },
    ],
    scripts,
    files: {
      'capacitor.config.ts': CAP_CONFIG(appId, appName, webDir),
      'MOBILE_EXPORT.md': README(appId, webDir, buildHint),
    },
    instructions: `Wrapped this app as a Capacitor mobile project (appId ${appId}, webDir ${webDir}). Add the dependencies and the scripts (${Object.keys(scripts).join(', ')}) to package.json, then: npm install → ${buildHint} → npx cap add android → npx cap sync. A SIGNED .apk/.aab/.ipa is NOT produced here — it needs the native SDK + your keystore on a build runner (see MOBILE_EXPORT.md).`,
  };
}
