// AI BUILD REPAIR — the second tier of the self-healing APK/AAB loop.
//
// WHY THIS EXISTS (admin 2026-08-03, verbatim): "jo claude code karta hai, woh navbharatai nahi kar
// sakta kya?" — and he is right. The deterministic tier (mobileBuildRepair.ts) only fixes failures it
// can NAME from a pattern list. Anything outside that list ended as "NavBharatAI could not fix this one
// on its own" — for an app NavBharatAI itself generated. Claude Code's actual loop is: read the failing
// log, read the files involved, write the fix, run again. This module gives NavBharatAI that same loop.
//
// TIERING (why the rules still run first): the deterministic repairs are instant, free, and 100%
// reliable for the classes they name — an LLM pass costs real tokens and seconds. So rules always get
// the first attempt, and the AI is the escalation for what the rules cannot name. That includes the
// USER'S OWN APP CODE: the admin's explicit direction — "jab app puri navbharatai ne banayi hai" — the
// app itself was generated by NavBharatAI, so repairing a compile error in it is fixing our own output,
// not editing a stranger's work. (This supersedes the earlier diagnose-only boundary for app code.)
//
// SAFETY MODEL — an AI edit is only ever accepted inside hard, code-enforced bounds:
//   • The model may ONLY rewrite files this module fetched and offered (allow-listed paths). A path it
//     invents — or any secrets/keystore/lockfile path — is rejected in validation, never written.
//   • Full-content replacement only, size-capped; no deletes, no new files, no shell.
//   • A reply that changes nothing is a MISS (honest "could not fix"), never an empty commit — the same
//     loop guard the deterministic tier has.
//   • Every accepted fix lands as a normal named commit in the user's repository — visible, revertable.
//   • Model chain per the Model Routing Policy's heal-gate row: flagship GLM → Kimi. NEVER Sonnet/Opus
//     (this route cannot see the user's tier, so it takes the weak-tier-safe path by construction).
//   • Kill switch: MOBILE_AUTOFIX_AI=off reverts to rules-only without a deploy.
//
// PURE where it matters: prompt building, reply validation, path extraction and sanitization are pure
// functions with no I/O, so every guard is unit-testable. The one LLM call is injected by the route.

export interface AiRepairContext {
  /** The failing step's log — already narrowed by failedStepSection, already timestamp-stripped. */
  log: string;
  /** Current contents of every file the model is allowed to see and rewrite. */
  files: Record<string, string>;
  /** What the deterministic tier concluded, so the model starts from the honest state. */
  ruleSummary: string;
}

export interface AiRepairFix {
  /** Full new contents, path → text. Only allow-listed paths survive validation. */
  files: Record<string, string>;
  /** One plain-language sentence for the user, already vendor-sanitized. */
  explanation: string;
}

/** A single model rung the route will try, in order. */
export interface AiRepairModel {
  provider: 'GLM' | 'KIMI';
  model: string;
  baseURL: string;
  apiKey: string;
}

/** Per-file and per-reply caps — a runaway model must not be able to write a megabyte into a repo. */
export const AI_REPAIR_MAX_FILE_CHARS = 300_000;
export const AI_REPAIR_MAX_FILES = 6;
/** How much of the failing log the model sees. Failures live at the end, so the TAIL is kept. */
export const AI_REPAIR_LOG_CHARS = 12_000;

/** Paths that must never be offered to or accepted from the model, whatever the log says. */
const FORBIDDEN_PATH = /(^|\/)(\.env[^/]*|.*\.(keystore|jks|p12|pem|key)|package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$/i;

/**
 * Source files the failing log itself names — the compile error tells us exactly which of the app's
 * files broke, and those are the ones worth showing the model. Bounded and deduplicated; forbidden
 * paths are dropped here so they are never even fetched.
 */
export function filesNamedInLog(log: string, cap = 4): string[] {
  const out: string[] = [];
  const re = /(?:^|[\s"'(\[])((?:src|app|pages|components|lib|public|www)\/[\w./-]+\.(?:tsx?|jsx?|mjs|cjs|css|scss|vue|json|html?))(?=$|[\s"':)\],(])/gim;
  for (const m of log.matchAll(re)) {
    const p = m[1];
    if (FORBIDDEN_PATH.test(p) || p.includes('..') || out.includes(p)) continue;
    out.push(p);
    if (out.length >= cap) break;
  }
  return out;
}

/**
 * The full set of repository paths the AI pass may read and rewrite for this failure: the workflow and
 * the packaging files NavBharatAI generated, plus whichever app source files the error names.
 */
export function aiRepairAllowedPaths(workflowPath: string, log: string): string[] {
  const base = [workflowPath, 'package.json', 'capacitor.config.ts'];
  const named = filesNamedInLog(log);
  return [...new Set([...base, ...named])].filter((p) => !FORBIDDEN_PATH.test(p)).slice(0, AI_REPAIR_MAX_FILES);
}

/**
 * The model chain, flagship-first per the heal-gate policy row. Empty when no cheap-coder key is
 * configured — the route then reports honestly instead of silently doing nothing.
 *
 * Keys may be comma-separated pools (the 429-rotation format); a single repair call just takes the
 * first key — rotation belongs to the build engine's pacer, not here.
 */
export function aiRepairModelChain(env: NodeJS.ProcessEnv = process.env): AiRepairModel[] {
  const chain: AiRepairModel[] = [];
  const firstKey = (raw?: string): string => (raw || '').split(',')[0].trim();

  const glmKey = firstKey(env.GLM_API_KEY);
  if (glmKey) {
    chain.push({
      provider: 'GLM',
      model: env.MOBILE_AUTOFIX_GLM_MODEL || 'glm-5.2',
      baseURL: env.GLM_BASE_URL || 'https://api.z.ai/api/paas/v4',
      apiKey: glmKey,
    });
  }
  const kimiKey = firstKey(env.KIMI_API_KEY);
  if (kimiKey) {
    chain.push({
      provider: 'KIMI',
      model: env.MOBILE_AUTOFIX_KIMI_MODEL || 'kimi-k2.7-code',
      baseURL: env.KIMI_BASE_URL || 'https://api.moonshot.ai/v1',
      apiKey: kimiKey,
    });
  }
  return chain;
}

export function aiRepairEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  return env.MOBILE_AUTOFIX_AI !== 'off';
}

/** System prompt — the contract the reply is validated against. */
export const AI_REPAIR_SYSTEM_PROMPT = [
  'You repair failed Android app builds for a non-technical user. You receive the failing step of a',
  'GitHub Actions log and the current contents of the files you are allowed to change.',
  '',
  'Reply with STRICT JSON only — no markdown, no prose outside the JSON:',
  '{"fixable": true, "explanation": "<one short sentence, plain language, no tool or vendor names>",',
  ' "files": {"<path>": "<the COMPLETE new content of that file>"}}',
  'or {"fixable": false, "explanation": "<one short sentence saying what is wrong>"}',
  '',
  'Rules:',
  '- Only include files you actually need to change, chosen ONLY from the provided files.',
  '- Each value is the ENTIRE new file content, not a diff.',
  '- Fix the root cause of the build failure; keep every unrelated line exactly as it is.',
  '- Never add secrets, tokens, keystores or signing configuration.',
  '- If the real cause is a missing signing key or anything outside these files, reply fixable:false.',
].join('\n');

/** The user prompt: the honest rule-tier verdict, the failing log tail, then every offered file. */
export function buildAiRepairPrompt(ctx: AiRepairContext): string {
  const log = ctx.log.length > AI_REPAIR_LOG_CHARS ? ctx.log.slice(-AI_REPAIR_LOG_CHARS) : ctx.log;
  const parts = [
    `Automated diagnosis so far: ${ctx.ruleSummary}`,
    '',
    '=== FAILING STEP LOG ===',
    log,
    '',
    '=== FILES YOU MAY CHANGE ===',
  ];
  for (const [path, content] of Object.entries(ctx.files)) {
    parts.push(`--- ${path} ---`, content.length > AI_REPAIR_MAX_FILE_CHARS ? content.slice(0, AI_REPAIR_MAX_FILE_CHARS) : content, '');
  }
  return parts.join('\n');
}

/**
 * Strip vendor/model identity from text the user will see (the White-Label Law). The model is told not
 * to name tools, but a guard the user's screen depends on is enforced in code, not requested politely.
 */
export function sanitizeAiText(text: string): string {
  return String(text || '')
    .replace(/\b(GLM|Z\.?AI|Kimi|Moonshot|Claude|Anthropic|Sonnet|Opus|Haiku|Gemini|Vertex|Grok|xAI|OpenAI|GPT[-\w.]*|DeepSeek|glm[-\w.]*|kimi[-\w.]*|claude[-\w.]*|gemini[-\w.]*|grok[-\w.]*)\b/gi, "NavBharatAI's engine")
    .replace(/(NavBharatAI's engine)(\s+\1)+/g, '$1')
    .trim()
    .slice(0, 300);
}

/**
 * Validate a model reply into an applied-or-rejected decision. Every rule here is a hard gate:
 * a reply that fails ANY of them yields null (or an honest fixable:false), never a partial write.
 */
export function parseAiRepairReply(
  raw: string,
  allowedPaths: string[],
  current: Record<string, string>,
): AiRepairFix | { fixable: false; explanation: string } | null {
  const text = String(raw || '');
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start < 0 || end <= start) return null;

  let parsed: unknown;
  try { parsed = JSON.parse(text.slice(start, end + 1)); } catch { return null; }
  if (!parsed || typeof parsed !== 'object') return null;
  const obj = parsed as { fixable?: unknown; explanation?: unknown; files?: unknown };

  const explanation = sanitizeAiText(typeof obj.explanation === 'string' ? obj.explanation : '');

  if (obj.fixable === false) {
    return { fixable: false, explanation: explanation || 'The problem is outside what can be repaired automatically.' };
  }
  if (obj.fixable !== true || !obj.files || typeof obj.files !== 'object') return null;

  const files: Record<string, string> = {};
  for (const [path, content] of Object.entries(obj.files as Record<string, unknown>)) {
    // Every gate is deliberate: unknown path → the model invented a file; forbidden → secrets;
    // non-string/empty/oversized → not a real file; unchanged → contributes nothing.
    if (!allowedPaths.includes(path)) return null;
    if (FORBIDDEN_PATH.test(path) || path.includes('..')) return null;
    if (typeof content !== 'string' || !content.trim()) return null;
    if (content.length > AI_REPAIR_MAX_FILE_CHARS) return null;
    if ((current[path] || '') === content) continue;
    files[path] = content;
  }
  // Everything it sent was identical to what is already there — that is a miss, not a fix; committing
  // it would re-run a build that fails the same way (the same loop guard as the deterministic tier).
  if (Object.keys(files).length === 0) return null;

  return { files, explanation: explanation || 'NavBharatAI found the problem in the build files and corrected it.' };
}

/** The injected LLM call — one prompt in, raw text out. The route provides the real HTTP client. */
export type AiRepairLlm = (model: AiRepairModel, system: string, prompt: string) => Promise<string>;

/**
 * Run the AI repair over the model chain. First model whose reply VALIDATES wins; a model that errors,
 * times out, or replies out-of-contract falls through to the next. Null = no rung produced a valid
 * fix — the caller reports honestly.
 */
export async function runAiRepair(
  llm: AiRepairLlm,
  chain: AiRepairModel[],
  ctx: AiRepairContext,
): Promise<AiRepairFix | { fixable: false; explanation: string } | null> {
  const prompt = buildAiRepairPrompt(ctx);
  for (const model of chain) {
    try {
      const reply = await llm(model, AI_REPAIR_SYSTEM_PROMPT, prompt);
      const result = parseAiRepairReply(reply, Object.keys(ctx.files), ctx.files);
      if (result) return result;
    } catch {
      // This rung failed or timed out — the next one gets its chance. Never the user's problem.
    }
  }
  return null;
}
