// THE OBJECT CATALOGUE — what games are actually made of.
//
// Admin, 2026-09-14: *"generally kisi app me kya kya object chahiye hote hai — uski ek detailed list
// banao (bike, car, train, plan, ground, nadi, talab, admi, animals, cycle, badal, road, tree)… list
// jitni badi hogi NavBharatAI ko utni hi asani hogi."*
//
// 🔴 THE REPORT BEHIND IT. A bike racing game whose bike was a red capsule on two grey cylinders. The
// realism system was innocent — `realismIntent.ts` read the intention correctly and `objects.ts`
// builds good things — but the LIBRARY HAD NO BIKE, so the standing order "use the library, never
// hand-model" was one the model could not obey. It improvised, and three primitives is what
// improvising produces. A list of eight objects meets its ninth request the same day.
//
// ⚠️ EVERY NUMBER IN THIS FILE IS A REAL-WORLD MEASUREMENT. They are the whole value: "about 2 m
// long" produces a toy; "2.05 m long, 1.35 m wheelbase, 0.30 m wheel radius" produces a bike. Do not
// round them to look tidy, and do not add an entry whose numbers you have not checked — a confident
// wrong dimension is worse than no entry at all, because the model will build to it.
//
// HOW TO GROW IT: add an entry with real dims, 4+ parts and a tell. `words` takes English and
// romanised Hindi; `hi` takes Devanagari and is matched WITHOUT `\b` (see objectCatalogTypes).
// Placement is inherited from the category — do not repeat it per object.

import type { CatalogEntry } from './objectCatalogTypes';

/** Things that drive. */
const VEHICLES_LAND: CatalogEntry[] = [
  { id: 'motorcycle', name: 'motorcycle', category: 'vehicle-land', builder: 'createMotorcycle',
    words: 'motorcycle|motorbike|motor\\s*bike|superbike|bike\\s*(?:racing|race|rider|riding|game)|racing\\s*bike|bullet|pulsar|scooty|scooter|moped|baik',
    hi: 'मोटरसाइकिल|बाइक|स्कूटी',
    dims: '2.05 m long, 0.72 m across the bars, 1.10 m tall, WHEELBASE 1.35 m, wheel radius 0.30 m, seat 0.80 m',
    parts: ['fuel tank', 'seat falling to a kicked-up tail', 'RAKED front forks (never vertical)', 'handlebar with grips and mirrors', 'engine block low and central', 'exhaust header into a can', 'swingarm and chain', 'front disc and caliper', 'mudguards over both wheels', 'headlight and tail light that EMIT'],
    tell: 'A motorcycle is mostly AIR — the wheels sit far apart with open daylight under the engine, and the tank-to-tail line falls backwards. A body blob bridging two cylinders has none of that, which is why it reads as a toy however good the lighting is.' },
  { id: 'bicycle', name: 'bicycle', category: 'vehicle-land', builder: 'createBicycle',
    words: 'bicycle|cycle|cycling|pedal\\s*bike|bmx|cyclist', hi: 'साइकिल',
    dims: '1.75 m long, 1.05 m wheelbase, wheel radius 0.34 m, saddle 0.96 m, bars 0.55 m wide',
    parts: ['open DIAMOND frame of thin tubes', 'two large thin wheels with visible spokes', 'saddle on a seat post', 'handlebars', 'chainring, cranks and pedals'],
    tell: 'It is NOT a small motorcycle. The frame is open tubing you can see the background through, the wheels are larger and far thinner, and there is no engine mass in the middle.' },
  { id: 'car', name: 'car', category: 'vehicle-land', builder: 'createCar',
    words: 'car|sedan|hatchback|suv|taxi|cab|gaadi|gadi|racing\\s*car|sports\\s*car', hi: 'कार|गाड़ी',
    dims: '4.3 m long, 1.8 m wide, 1.45 m tall, wheelbase 2.6 m, wheel radius 0.32 m',
    parts: ['cabin narrower and higher than the body', 'raked windscreen with dark glass', 'bonnet and boot LOWER than the cabin', 'wheel arches', 'separate tyre and rim', 'grille and bumpers', 'headlights and tail lights that EMIT', 'door lines and mirrors'],
    tell: 'The STEP between the low bonnet, the higher cabin and the low boot is the car’s outline. A single box on wheels is a van at car scale.' },
  { id: 'auto-rickshaw', name: 'auto-rickshaw', category: 'vehicle-land',
    words: 'auto\\s*-?\\s*rickshaw|rickshaw|autorickshaw|tuk\\s*-?\\s*tuk|three\\s*wheeler|tempo', hi: 'ऑटो|रिक्शा',
    dims: '2.6 m long, 1.3 m wide, 1.7 m tall, THREE wheels (one front, two rear), wheel radius 0.20 m',
    parts: ['single front wheel under a fork', 'canvas roof on thin posts', 'OPEN sides with no doors', 'bench seat visible from outside', 'handlebar steering, not a wheel', 'yellow-and-green or black-and-yellow paint'],
    tell: 'The three-wheel stance and the open sides are the silhouette — you can see straight THROUGH it, which no car does.' },
  { id: 'bus', name: 'bus', category: 'vehicle-land',
    words: 'bus|coach|minibus|school\\s*bus', hi: 'बस',
    dims: '11 m long, 2.5 m wide, 3.2 m tall, wheelbase 5.6 m, wheel radius 0.50 m',
    parts: ['a long flat-sided box with a flat front', 'a ROW of windows the full length at one height', 'a door with steps', 'large wheels partly hidden by the body', 'destination board above the windscreen'],
    tell: 'The window band running the whole length at a constant height is what makes it a bus rather than a large van.' },
  { id: 'truck', name: 'truck', category: 'vehicle-land',
    words: 'truck|lorry|tipper|trailer|semi|container\\s*truck', hi: 'ट्रक',
    dims: '8.5 m long, 2.5 m wide, 3.4 m tall, wheel radius 0.52 m, 6 wheels (2 front, 4 rear doubled)',
    parts: ['a SEPARATE cab and cargo body with a visible gap between them', 'cab taller than it is long', 'rear wheels doubled', 'tall exhaust stack', 'mudflaps and a heavy bumper'],
    tell: 'The gap between the cab and the load body is the defining line. One continuous box is a bus.' },
  { id: 'tractor', name: 'tractor', category: 'vehicle-land',
    words: 'tractor|farm\\s*vehicle|trolley\\s*tractor', hi: 'ट्रैक्टर',
    dims: '3.6 m long, 2.0 m wide, 2.6 m tall, REAR wheel radius 0.75 m, FRONT wheel radius 0.40 m',
    parts: ['rear wheels almost twice the front ones', 'deep chevron tread on the rear tyres', 'narrow bonnet with an exhaust stack in front of the driver', 'open seat above the rear axle', 'mudguards over the rear wheels'],
    tell: 'The huge-rear, small-front wheel mismatch IS the tractor. Equal wheels make it a truck.' },
  { id: 'train', name: 'train / locomotive', category: 'vehicle-land',
    words: 'train|locomotive|railway|metro|rail\\s*engine|coach|wagon', hi: 'ट्रेन|रेल|रेलगाड़ी',
    dims: 'locomotive 20 m long, 3.0 m wide, 4.0 m tall; each coach 22 m; track gauge 1.676 m; rail height 0.17 m',
    parts: ['bogies (wheel trucks) under each END, not wheels along the body', 'a long unbroken flank', 'cab windows only at the ends', 'couplings between units', 'rails on sleepers on ballast beneath'],
    tell: 'Length to height is about 5:1 and the wheels are grouped into bogies. Evenly spaced wheels along the body reads as a toy train.' },
  { id: 'jeep', name: 'jeep / off-roader', category: 'vehicle-land',
    words: 'jeep|off\\s*-?\\s*roader|4x4|thar|land\\s*rover|pickup', hi: 'जीप',
    dims: '4.2 m long, 1.9 m wide, 1.85 m tall, wheelbase 2.45 m, wheel radius 0.40 m, ground clearance 0.22 m',
    parts: ['high ground clearance with visible suspension', 'flat upright windscreen', 'exposed wheel arches and chunky tread', 'a spare wheel on the back', 'roll bar or hard top', 'a flat slab bonnet'],
    tell: 'It is TALL and upright with big gaps around the wheels. A car silhouette with big tyres is not a jeep.' },
  { id: 'emergency-vehicle', name: 'ambulance / fire engine / police car', category: 'vehicle-land',
    words: 'ambulance|fire\\s*(?:engine|truck|brigade)|police\\s*(?:car|van|jeep)', hi: 'एम्बुलेंस|दमकल|पुलिस\\s*गाड़ी',
    dims: 'ambulance 5.6 m long, 2.1 m wide, 2.6 m tall; fire engine 9 m long, 2.5 m wide, 3.3 m tall',
    parts: ['a light bar that FLASHES on the roof', 'high-visibility livery in bands, not a plain colour', 'a tall box body behind a normal cab', 'rear doors that read as openable', 'ladder or hose reels (fire engine)'],
    tell: 'The flashing light bar and the banded livery are the whole read — a plain white van with a red cross painted on is a van.' },
  { id: 'cart', name: 'bullock cart / handcart', category: 'vehicle-land',
    words: 'bullock\\s*cart|ox\\s*cart|hand\\s*cart|thela|cart|tonga|carriage', hi: 'बैलगाड़ी|ठेला|तांगा',
    dims: '2.8 m long, 1.5 m wide, wheel radius 0.55 m, bed 0.9 m off the ground, shafts 2.0 m',
    parts: ['two large spoked WOODEN wheels', 'an open flat bed with side rails', 'two shafts reaching forward to the animal or handles', 'a wooden axle visible under the bed'],
    tell: 'Enormous thin spoked wheels relative to a small bed, and the shafts reaching forward. Small wheels make it a trolley.' },
  { id: 'construction-vehicle', name: 'bulldozer / excavator / crane', category: 'vehicle-land',
    words: 'bulldozer|excavator|jcb|digger|crane|dumper|loader|road\\s*roller', hi: 'बुलडोजर|क्रेन',
    dims: 'excavator 7.5 m long, 2.8 m wide, 3.0 m tall, boom reach 9 m; bulldozer blade 3.4 m wide',
    parts: ['continuous TRACKS or very large tyres', 'a cab offset to one side, not centred', 'a hydraulic arm or blade with visible rams', 'counterweight at the back', 'yellow paint with wear and dirt'],
    tell: 'The working arm is as large as the machine, and the cab sits off-centre. A symmetrical yellow box is not construction plant.' },
  { id: 'tank', name: 'tank', category: 'vehicle-land',
    words: 'tank|armou?red\\s*vehicle|battle\\s*tank|apc', hi: 'टैंक',
    dims: 'hull 7.0 m long, 3.6 m wide, 2.4 m tall; barrel 5.0 m; tracks 0.6 m wide',
    parts: ['a turret that ROTATES independently of the hull', 'a long thin barrel with a muzzle brake', 'continuous tracks over road wheels, idler and drive sprocket', 'sloped frontal armour', 'a commander’s hatch'],
    tell: 'The barrel is nearly the vehicle’s length again, and the tracks wrap over visibly separate road wheels. Smooth track slabs read as rubber skirts.' },
  { id: 'kart', name: 'go-kart / ATV', category: 'vehicle-land',
    words: 'go\\s*-?\\s*kart|kart|quad\\s*bike|atv|buggy', hi: 'कार्ट',
    dims: 'kart 1.9 m long, 1.4 m wide, 0.65 m tall, wheel radius 0.14 m front / 0.17 m rear',
    parts: ['an open tubular frame with no bodywork above the axles', 'a seat right on the floor pan', 'exposed wheels outside the frame', 'a small engine hanging off one side', 'a steering wheel on a long exposed column'],
    tell: 'The driver sits almost ON the ground and the wheels are entirely outside the body. Enclosed bodywork makes it a small car.' },
];

/** Things that fly. */
const VEHICLES_AIR: CatalogEntry[] = [
  { id: 'aeroplane', name: 'aeroplane', category: 'vehicle-air',
    words: 'aeroplane|airplane|aircraft|plane|jet|flight\\s*sim(?:ulator)?|fighter\\s*jet|airliner', hi: 'हवाई\\s*जहाज|विमान',
    dims: 'airliner 40 m long, wingspan 35 m, 12 m tall; fighter 16 m long, wingspan 11 m',
    parts: ['wings SWEPT back, mounted low on the fuselage', 'a vertical tail fin plus a horizontal tailplane', 'engines under the wings (airliner) or in the fuselage (fighter)', 'cockpit glazing at the nose', 'retractable landing gear', 'navigation lights at the wingtips'],
    tell: 'Wingspan is close to the fuselage LENGTH. Short stubby wings are the commonest mistake and make it read as a paper toy.' },
  { id: 'helicopter', name: 'helicopter', category: 'vehicle-air',
    words: 'helicopter|chopper|heli', hi: 'हेलीकॉप्टर',
    dims: '13 m long including the boom, main rotor diameter 11 m, 3.5 m tall',
    parts: ['a main rotor WIDER than the body is long', 'a thin tail boom with a VERTICAL tail rotor', 'bubble cockpit glazing', 'skids or wheels', 'an engine housing behind the rotor mast'],
    tell: 'The rotor disc is enormous relative to the fuselage, and the tail rotor faces sideways. A small rotor makes it a toy instantly.' },
  { id: 'drone', name: 'drone', category: 'vehicle-air',
    words: 'drone|quad\\s*copter|quadcopter|uav', hi: 'ड्रोन',
    dims: '0.45 m across the motors, 0.12 m tall, propeller diameter 0.24 m',
    parts: ['FOUR arms in an X from a central body', 'a motor and propeller at each arm tip', 'a camera gimbal slung below', 'landing legs', 'status LEDs'],
    tell: 'The arms are clearly separate from the body and the propeller discs overlap nothing. A blob with fans on top is not a drone.' },
  { id: 'rocket', name: 'rocket / spaceship', category: 'vehicle-air',
    words: 'rocket|spaceship|space\\s*craft|spacecraft|launch\\s*vehicle|space\\s*shuttle|ufo', hi: 'रॉकेट|अंतरिक्ष\\s*यान',
    dims: 'rocket 50 m tall, 3.7 m diameter, fins 3 m span, engine bell 2.4 m',
    parts: ['a tapered nose cone', 'a long unbroken cylindrical body', 'stage separation lines', 'fins at the base', 'engine bells recessed under the tail'],
    tell: 'Height is roughly thirteen times the diameter. A short fat cylinder reads as a firework.' },
  { id: 'balloon', name: 'hot air balloon / parachute', category: 'vehicle-air',
    words: 'hot\\s*air\\s*balloon|balloon\\s*ride|parachute|paraglider|glider', hi: 'गुब्बारा|पैराशूट',
    dims: 'balloon envelope 18 m tall, 15 m wide, basket 1.2 m cube hung 3 m below; parachute canopy 7 m span',
    parts: ['an envelope far larger than what hangs below it', 'visible gore panels in alternating colours', 'thin lines from the canopy to the load', 'a basket or harness', 'a burner flame (balloon)'],
    tell: 'The canopy dwarfs the payload and the connecting lines are thin and many. A solid stalk between them looks like a lamp.' },
];

/** Things that float. */
const VEHICLES_WATER: CatalogEntry[] = [
  { id: 'boat', name: 'boat', category: 'vehicle-water',
    words: 'boat|dinghy|canoe|kayak|speedboat|fishing\\s*boat|naav|nauka|ferry', hi: 'नाव|नौका',
    dims: '5.0 m long, 1.8 m wide, 1.2 m tall at the bow, draught 0.35 m',
    parts: ['a V-shaped bow narrowing to a point', 'a flat transom at the stern', 'a hull that curves UP toward the bow (sheer)', 'bench seats across the beam', 'an outboard motor or oars', 'a visible waterline'],
    tell: 'The bow narrows to a POINT and the stern is cut flat. A symmetrical box floats like a crate, not a boat.' },
  { id: 'ship', name: 'ship', category: 'vehicle-water',
    words: 'ship|cargo\\s*ship|tanker|cruise\\s*ship|warship|naval|steamer', hi: 'जहाज',
    dims: 'cargo ship 180 m long, 28 m beam, 14 m freeboard, superstructure 8 decks',
    parts: ['a bulbous bow below the waterline', 'the superstructure set well AFT, not centred', 'a funnel above the superstructure', 'containers or deck cranes', 'a waterline with different paint below'],
    tell: 'Length is six to eight times the beam, and the accommodation block sits near the stern. A centred box is a ferry at best.' },
  { id: 'submarine', name: 'submarine', category: 'vehicle-water',
    words: 'submarine|sub\\s*marine|u\\s*-?\\s*boat', hi: 'पनडुब्बी',
    dims: '70 m long, 7 m diameter, conning tower 5 m tall',
    parts: ['a smooth cigar hull with NO flat surfaces', 'a conning tower forward of centre', 'dive planes on the tower and the tail', 'a cruciform tail with a propeller', 'flooding vents along the top'],
    tell: 'It is one continuous rounded form with a single tower. Flat panels and windows make it a boat.' },
];

/** People. */
const CHARACTERS: CatalogEntry[] = [
  { id: 'human', name: 'human character', category: 'character', builder: 'createHumanoid',
    words: 'player|character|person|human|hero|man|woman|avatar|runner|aadmi|insaan|ladka|ladki|villager|crowd',
    hi: 'आदमी|इंसान|खिलाड़ी|व्यक्ति|लड़का|लड़की',
    dims: '1.75 m tall; head is 1/7.5 of height; shoulders 0.45 m; legs are HALF the total height; hand 0.18 m',
    parts: ['separate head, torso, upper and lower arms, upper and lower legs', 'knees that bend ONE way only', 'arms that swing OPPOSITE the legs', 'hands and feet as distinct masses', 'a neck between head and shoulders'],
    tell: 'Legs are HALF the total height and the head is small. A capsule with a sphere on top is the single clearest sign of an AI-generated game.' },
  { id: 'child', name: 'child', category: 'character', builder: 'createHumanoid',
    words: 'child|kid|boy|girl|baby|bachcha|toddler', hi: 'बच्चा|बच्ची',
    dims: '1.20 m tall at age 7; head is 1/6 of height (proportionally MUCH larger than an adult’s); legs 0.55 m',
    parts: ['a proportionally larger head', 'shorter limbs relative to the torso', 'a rounder body with less shoulder width', 'a shorter stride and faster step rate'],
    tell: 'A child is NOT a scaled-down adult — the head is a bigger fraction of the height. Uniform scaling produces a tiny adult, which reads as uncanny.' },
  { id: 'uniformed', name: 'soldier / police / worker', category: 'character', builder: 'createHumanoid',
    words: 'soldier|army|police|policeman|guard|worker|farmer|doctor|nurse|shopkeeper|driver|kisan',
    hi: 'सैनिक|पुलिस|किसान|डॉक्टर|मजदूर|दुकानदार',
    dims: 'as a human, 1.75 m; helmet adds 0.06 m; a backpack adds 0.25 m depth',
    parts: ['a uniform in ONE consistent colour with belts or straps breaking it up', 'headgear (helmet, cap, turban)', 'footwear distinct from the legs', 'the tools of the role (weapon, stethoscope, sickle) held in the HAND', 'an insignia or badge patch'],
    tell: 'The silhouette must change with the role — a backpack, a helmet, a held tool. Recolouring the same body reads as a palette swap.' },
  { id: 'creature', name: 'zombie / robot / alien / skeleton', category: 'character', builder: 'createHumanoid',
    words: 'zombie|robot|android|alien|skeleton|monster|ghost|mummy|undead|boss\\s*enemy', hi: 'रोबोट|भूत|राक्षस',
    dims: 'humanoid 1.75–2.2 m; robot joints 0.12 m; a boss is 1.5–2× the player, never more (it must fit the camera)',
    parts: ['a deliberately BROKEN human proportion — longer arms, a hunch, a tilted head', 'a distinct movement rhythm (shuffle, servo snap, drift)', 'an emissive feature (eyes, core, seams) so it reads in the dark', 'visible damage or construction seams'],
    tell: 'It must be recognisably off-human at silhouette size. A normal human in green paint is a costume, not a creature.' },
];

/** Animals. */
const ANIMALS: CatalogEntry[] = [
  { id: 'horse', name: 'horse', category: 'animal', builder: "createAnimal({ kind: 'horse' })",
    words: 'horse|ghoda|stallion|mare|pony|riding\\s*horse', hi: 'घोड़ा',
    dims: '2.4 m nose to tail, 0.7 m wide, 1.6 m at the withers, legs 0.9 m',
    parts: ['a deep chest tapering to a narrower rump', 'a long neck angled up from the shoulders', 'a head with a distinct muzzle', 'hind legs whose hocks bend BACKWARDS', 'mane and tail'],
    tell: 'It moves on DIAGONAL pairs — front-left with rear-right. All four legs in phase reads as a toy being dragged.' },
  { id: 'cow', name: 'cow / buffalo / bull', category: 'animal', builder: "createAnimal({ kind: 'cow' })",
    words: 'cow|buffalo|bull|ox|bail|gaay|cattle|calf', hi: 'गाय|भैंस|बैल',
    dims: '2.4 m long, 0.8 m wide, 1.5 m at the shoulder, legs 0.8 m; horns 0.3 m',
    parts: ['a heavy barrel body much deeper than a horse’s', 'a head carried LOW, near shoulder height', 'horns and large ears', 'a hump (Indian breeds) over the shoulders', 'a tail with a tuft'],
    tell: 'The head hangs LOW and the body is a heavy barrel. A horse body with horns is not a cow.' },
  { id: 'dog', name: 'dog / cat', category: 'animal', builder: "createAnimal({ kind: 'dog' })",
    words: 'dog|puppy|kutta|street\\s*dog|cat|billi|kitten', hi: 'कुत्ता|बिल्ली',
    dims: 'dog 0.9 m long, 0.6 m at the shoulder; cat 0.5 m long, 0.25 m at the shoulder',
    parts: ['a head with a muzzle and upright or folded ears', 'a springy back that flexes when running', 'a tail that moves independently', 'paws as distinct masses'],
    tell: 'The spine FLEXES as it runs — a rigid back is what makes a small animal read as a wind-up toy.' },
  { id: 'elephant', name: 'elephant', category: 'animal',
    words: 'elephant|hathi|haathi', hi: 'हाथी',
    dims: '6.0 m long, 2.0 m wide, 3.2 m at the shoulder, legs 1.6 m, trunk 2.0 m',
    parts: ['a trunk reaching near the ground', 'ears as large flat sheets', 'PILLAR legs of near-constant thickness', 'a domed head and forehead', 'tusks and a thin tail'],
    tell: 'The legs are PILLARS, not tapered animal legs, and the ears are almost as tall as the head. Tapered legs make it a large cow.' },
  { id: 'big-cat', name: 'tiger / lion / leopard', category: 'animal', builder: "createAnimal({ kind: 'deer' })",
    words: 'tiger|lion|leopard|panther|cheetah|sher|bagh', hi: 'बाघ|शेर|चीता',
    dims: '2.8 m nose to tail, 1.0 m at the shoulder, 0.9 m wide at the chest',
    parts: ['heavy shoulders higher than the hips', 'a long heavy tail nearly the body length', 'large paws', 'a broad flat head low to the ground', 'a mane (lion) or stripe/spot pattern in the material'],
    tell: 'The shoulders are the highest point and the tail is nearly as long as the body. A deer silhouette with stripes is not a tiger.' },
  { id: 'goat', name: 'goat / sheep / deer', category: 'animal', builder: "createAnimal({ kind: 'deer' })",
    words: 'goat|sheep|bakri|deer|hiran|antelope|lamb', hi: 'बकरी|भेड़|हिरण',
    dims: 'goat 1.3 m long, 0.8 m at the shoulder; deer 1.8 m long, 1.2 m at the shoulder',
    parts: ['thin legs relative to the body', 'a small head with horns or antlers', 'a short flicking tail', 'a neck carried upright and alert'],
    tell: 'Very thin legs under a light body, and a head that lifts to look around. Thick legs make it a cow.' },
  { id: 'camel', name: 'camel', category: 'animal',
    words: 'camel|oont|unt', hi: 'ऊंट',
    dims: '3.0 m long, 2.1 m at the hump, legs 1.3 m, neck 1.0 m',
    parts: ['one or two humps', 'a long curved neck carried in an S', 'very long legs with visible knee pads', 'broad flat feet', 'a small head with a drooping lip'],
    tell: 'Extremely long legs and a neck that curves rather than straightens. A horse with a hump is not a camel.' },
  { id: 'monkey', name: 'monkey', category: 'animal',
    words: 'monkey|bandar|ape|langur|chimp', hi: 'बंदर',
    dims: '0.6 m body, tail 0.7 m, arms nearly as long as the body',
    parts: ['arms as long as or longer than the legs', 'a long tail used for balance', 'hands and feet that grip', 'a flat face with a distinct muzzle'],
    tell: 'The arms are as long as the legs — that ratio is the whole read. Human proportions make it a small person.' },
  { id: 'bird', name: 'bird', category: 'animal',
    words: 'bird|eagle|crow|pigeon|parrot|flappy|chidiya|sparrow|peacock|owl', hi: 'पक्षी|चिड़िया|कौआ|मोर',
    dims: 'body 0.35 m, wingspan 1.2 m, tail 0.2 m; pigeon 0.32 m span 0.62 m',
    parts: ['WIDE thin wings hinged at the body and bending at a wrist', 'a tail fan used to steer', 'a small head with a beak', 'legs tucked in flight, extended on landing'],
    tell: 'Wingspan is three to four times the body length, and the wings BEND rather than staying flat boards.' },
  { id: 'fish', name: 'fish', category: 'animal',
    words: 'fish|shark|machli|aquarium|dolphin|whale', hi: 'मछली',
    dims: 'fish 0.40 m long, 0.12 m tall, 0.06 m wide; shark 3.5 m; dolphin 2.5 m',
    parts: ['a body flattened SIDE to side, not top to bottom', 'a forked or fan tail fin', 'a dorsal fin on top', 'paired pectoral fins', 'a gill line and an eye'],
    tell: 'The cross-section is TALL and narrow, and the tail sweeps side to side (a dolphin’s sweeps up and down). A rounded tube is a submarine.' },
  { id: 'insect', name: 'butterfly / bee / insect', category: 'animal',
    words: 'butterfly|bee|insect|dragonfly|firefly|titli|makkhi|ant|spider', hi: 'तितली|मधुमक्खी|चींटी',
    dims: 'butterfly 0.09 m span, bee 0.025 m long, dragonfly 0.10 m span',
    parts: ['SIX legs (eight for a spider) attached to the middle body section', 'a body in three visible segments', 'thin transparent or patterned wings', 'antennae'],
    tell: 'Three body segments with the legs on the middle one. Four legs or legs on the abdomen reads as a creature nobody can name.' },
  { id: 'snake', name: 'snake', category: 'animal',
    words: 'snake|serpent|saanp|cobra|python', hi: 'सांप|साँप',
    dims: '1.8 m long, 0.06 m thick, head 0.09 m',
    parts: ['a continuous body that tapers to the tail', 'a head slightly wider than the neck', 'a scale pattern in the material', 'a body that curves in a travelling S-wave'],
    tell: 'It moves as a travelling WAVE down the body, and the whole length stays on the ground. A rigid tube sliding forward reads as a pipe.' },
  { id: 'dinosaur', name: 'dinosaur / dragon', category: 'animal',
    words: 'dinosaur|dino|t\\s*-?\\s*rex|raptor|dragon|dragon\\s*boss', hi: 'डायनासोर|ड्रैगन',
    dims: 'T-rex 12 m long, 4 m at the hip, head 1.5 m; dragon wingspan 2× body length',
    parts: ['a long heavy tail balancing the body over the hips', 'a body carried HORIZONTALLY, not upright', 'a large head with visible jaw structure', 'powerful hind legs and small forelimbs', 'wings hinged at the shoulders (dragon)'],
    tell: 'The body is horizontal and the tail counterweights the head over the hips. An upright, tail-dragging pose is a 1950s illustration, not an animal.' },
];

export const CATALOG_PART_1: CatalogEntry[] = [
  ...VEHICLES_LAND, ...VEHICLES_AIR, ...VEHICLES_WATER, ...CHARACTERS, ...ANIMALS,
];

/** The world itself — the ground everything else stands on and raycasts against. */
const TERRAIN: CatalogEntry[] = [
  { id: 'ground', name: 'ground / terrain', category: 'terrain', builder: 'createTerrain',
    words: 'ground|terrain|land|floor|field|maidan|zameen|plain|meadow|grass\\s*land|farm|khet',
    hi: 'ज़मीन|जमीन|मैदान|खेत|भूमि',
    dims: 'playable area 200-500 m across; a visible horizon needs 1-2 km of terrain or fog; slopes under 30 degrees are walkable',
    parts: ['height variation from seeded noise, never a flat plane', 'a surface material with bump and roughness, never one flat colour', 'a walkable flat zone where play happens', 'distant relief so the horizon is not a straight line', 'fog matched to the lighting preset'],
    tell: 'A perfectly flat, single-coloured plane is the most artificial thing a 3D scene can contain — everything standing on it inherits the fakeness.' },
  { id: 'road', name: 'road', category: 'terrain', builder: 'createRoad',
    words: 'road|street|highway|lane|track|path|sadak|raasta|rasta|driveway', hi: 'सड़क|रास्ता',
    dims: 'lane 3.5 m wide, two-lane road 7 m plus 1.5 m shoulders; markings 0.10 m wide; kerb 0.15 m high',
    parts: ['lane markings as a TEXTURE on the surface, never floating strips', 'a kerb or shoulder edge where it meets the ground', 'a slightly darker, smoother material than the surrounding land', 'wear: tyre polish in the wheel tracks, patches, cracks', 'the road following the terrain height, not cutting through it'],
    tell: 'The EDGE is what sells it — a kerb, a gravel shoulder, a worn margin. A grey strip laid on grass with a hard edge reads as a ribbon.' },
  { id: 'mountain', name: 'mountain / hill', category: 'terrain', builder: 'createMountain',
    words: 'mountain|hill|peak|cliff|valley|canyon|pahad|parvat|slope|ridge', hi: 'पहाड़|पर्वत|घाटी',
    dims: 'a background mountain reads at 100-300 m tall and 2-5x as wide; a climbable hill 20-60 m',
    parts: ['an IRREGULAR ridge line, never a smooth cone', 'exposed rock where the slope is steepest', 'snow or lighter rock only above a consistent line', 'smaller foothills at the base', 'atmospheric haze increasing with distance'],
    tell: 'Distance haze is what creates scale — a mountain rendered at full contrast sits in the same space as the player and looks like a prop three metres away.' },
  { id: 'desert', name: 'desert / dunes', category: 'terrain', builder: 'createDesert',
    words: 'desert|dune|sand\\s*dune|sahara|thar|registan', hi: 'रेगिस्तान|रेत',
    dims: 'dunes 5-30 m tall, 50-200 m between crests; the windward slope is gentle, the slip face is about 34 degrees',
    parts: ['asymmetric dunes — a long gentle windward side and a short steep slip face', 'wind ripples in the surface material', 'a sand material with strong bump and near-zero metalness', 'sparse cacti, rocks and dried grass', 'heat haze or bright fog at the horizon'],
    tell: 'Dune ASYMMETRY. Symmetrical mounds of sand look like a beach; the steep slip face on one side is what makes it a desert.' },
  { id: 'beach', name: 'beach / coast / island', category: 'terrain',
    words: 'beach|coast|shore|island|seaside|tropical', hi: 'समुद्र\\s*तट|द्वीप',
    dims: 'beach 20-60 m from waterline to vegetation; the wet band is 3-8 m wide',
    parts: ['a WET darker band where waves reach, and a dry lighter band above it', 'a gentle slope into the water, never a cliff edge', 'debris at the high-water line — shells, weed, driftwood', 'palms and grasses set back from the water', 'foam where the water meets the sand'],
    tell: 'The wet band and the foam line. A dry beach meeting water at a hard edge is the single most obvious "placed plane" in any scene.' },
  { id: 'cave', name: 'cave / tunnel', category: 'terrain',
    words: 'cave|cavern|tunnel|mine|underground|gufa', hi: 'गुफा|सुरंग',
    dims: 'a walkable passage is 3-5 m wide and 3-4 m high; a chamber 15-40 m across',
    parts: ['an irregular non-repeating cross section', 'stalactites above and stalagmites below, never matching pairs', 'a light source inside — torches, glowing crystals, a shaft of daylight', 'wet dark patches and dripping', 'a floor with rubble, not a clean plane'],
    tell: 'The lighting IS the cave. An evenly lit tunnel reads as a corridor; pools of light with real darkness between them is what makes it underground.' },
  { id: 'snow', name: 'snow / ice', category: 'terrain',
    words: 'snow|ice|glacier|winter|frozen|barf|himalaya', hi: 'बर्फ',
    dims: 'snow depth 0.1-1.5 m; ice sheets 2-20 m across; footprints 0.03-0.15 m deep',
    parts: ['snow ACCUMULATING on upward faces only — roofs, branches, ledges — never on vertical walls', 'footprints and tracks that persist', 'ice as a separate near-transparent, highly reflective material', 'drifts piled against obstacles', 'a cold blue-shifted light and fog'],
    tell: 'Snow settles only where it can rest. Uniformly white objects including their undersides is what makes snow look like paint.' },
];

/** Water, in all the forms a game asks for. */
const WATER: CatalogEntry[] = [
  { id: 'river', name: 'river / stream', category: 'water', builder: 'createRiver',
    words: 'river|stream|creek|canal|nadi|nala|brook', hi: 'नदी|नाला',
    dims: 'a small river is 8-25 m wide and 1-3 m deep; a stream 1-4 m wide; banks drop 0.5-2 m',
    parts: ['a surface that MOVES in the flow direction every frame', 'banks that are wet and darker at the edge', 'water that deepens in colour toward the middle', 'rocks and reeds breaking the surface', 'foam or ripples where it passes obstacles'],
    tell: 'A river must FLOW — the surface has a direction. A still blue ribbon laid on grass is what "fake water" looks like, and no amount of colour fixes it.' },
  { id: 'pond', name: 'pond / lake / talab', category: 'water',
    words: 'pond|lake|talab|pokhar|reservoir|water\\s*body|jheel', hi: 'तालाब|झील|पोखर',
    dims: 'village pond 15-40 m across, 1-3 m deep; a lake 100 m and up; bank slope gentle over 2-5 m',
    parts: ['a still surface with SLOW ripples, not a flow direction', 'a muddy, reedy margin rather than a hard edge', 'reflections of the sky and the bank (needs applyEnvironment)', 'lotus, lilies or weed near the edges', 'steps or a ghat if it is a village pond'],
    tell: 'A pond is defined by its REFLECTION and its soft edge. A flat blue disc with a crisp rim is a painted circle on the ground.' },
  { id: 'sea', name: 'sea / ocean', category: 'water',
    words: 'sea|ocean|samundar|samandar|waves|open\\s*water', hi: 'समुद्र|सागर|लहर',
    dims: 'extends past the far plane; swell 0.5-3 m high with 20-60 m between crests',
    parts: ['a large-scale swell PLUS small-scale ripples — two frequencies, never one', 'foam on the wave crests', 'colour that changes with view angle and depth', 'a horizon line that meets the sky haze, not a hard cut', 'floating objects that rise and fall with the swell'],
    tell: 'Two scales of motion at once. A single sine wave over the whole ocean reads as corrugated plastic.' },
  { id: 'waterfall', name: 'waterfall', category: 'water',
    words: 'waterfall|falls|cascade|jharna', hi: 'झरना|जलप्रपात',
    dims: 'a scenic fall is 8-60 m tall and 3-15 m wide; the spray plume rises 3-10 m from the base',
    parts: ['a falling sheet with vertically scrolling texture', 'MIST and spray particles at the base, not a clean impact', 'churned white water in the plunge pool', 'wet darkened rock beside the flow', 'looping sound tied to distance'],
    tell: 'The spray at the bottom is what sells it. Water hitting a surface and simply stopping is the giveaway.' },
];

/** Plants. */
const VEGETATION: CatalogEntry[] = [
  { id: 'tree', name: 'tree', category: 'vegetation', builder: 'createTree',
    words: 'tree|trees|forest|jungle|ped|banyan|neem|mango\\s*tree|oak|pine|woods', hi: 'पेड़|जंगल|वृक्ष',
    dims: 'a mature tree is 8-20 m tall with a canopy 60-80% of its height across; trunk 0.3-0.8 m thick',
    parts: ['a trunk that TAPERS and is never perfectly straight', 'branches that split and thin as they rise', 'a canopy with an irregular outline, never a sphere', "bark material with real bump (surfaceMaterial('bark'))", 'roots flaring where the trunk meets the ground'],
    tell: 'The canopy outline must be IRREGULAR and the trunk must taper. A cylinder with a green ball on top is the most recognisable placeholder in all of 3D.' },
  { id: 'palm', name: 'palm tree', category: 'vegetation',
    words: 'palm|coconut\\s*tree|date\\s*palm|nariyal', hi: 'नारियल|ताड़',
    dims: '12-25 m tall, trunk 0.35 m thick and CURVED, fronds 3-5 m long',
    parts: ['a slender trunk with ring scars, leaning rather than vertical', 'fronds radiating from a single crown point', 'each frond drooping under its own weight', 'coconuts clustered at the crown', 'no branches at all'],
    tell: 'All the leaves come from ONE point at the top and droop. Branching makes it a normal tree with strange leaves.' },
  { id: 'bush', name: 'bush / shrub / hedge', category: 'vegetation',
    words: 'bush|shrub|hedge|jhaadi|jhadi|undergrowth', hi: 'झाड़ी',
    dims: '0.5-2.0 m tall and roughly as wide; a hedge 1-2 m tall in a continuous run',
    parts: ['many small leaf clusters, not one mass', 'an irregular silhouette with gaps to see through', 'a darker interior where light does not reach', 'a base that meets the ground with no gap'],
    tell: 'You must be able to see THROUGH parts of it. A solid opaque blob is a rock painted green.' },
  { id: 'grass', name: 'grass', category: 'vegetation',
    words: 'grass|lawn|turf|ghaas|meadow\\s*grass|weeds', hi: 'घास',
    dims: 'blades 0.1-0.4 m tall, in clumps of 20-60 blades; a lawn needs 5,000+ instances to read',
    parts: ['thin blades in CLUMPS, never evenly spread', 'varied height and lean within a clump', 'a slow wind sway', 'bare patches and a ground texture that matches underneath', 'shorter, sparser grass near paths'],
    tell: 'Clumping plus wind. An even carpet of identical upright blades reads as a doormat.' },
  { id: 'flower', name: 'flower / plant', category: 'vegetation',
    words: 'flower|flowers|plant|pot\\s*plant|garden|phool|rose|lotus|sunflower', hi: 'फूल|पौधा|कमल',
    dims: 'a garden flower stands 0.3-1.0 m; the bloom is 0.05-0.15 m; a sunflower 2 m with a 0.25 m head',
    parts: ['a stem thinner than the bloom', 'petals as separate surfaces, not a disc', 'leaves lower on the stem', 'a centre of a different colour and material'],
    tell: 'Petals must be SEPARATE and slightly varied. A coloured disc on a stick is a lollipop.' },
  { id: 'cactus', name: 'cactus', category: 'vegetation',
    words: 'cactus|cacti|succulent|nagphani', hi: 'कैक्टस|नागफनी',
    dims: 'saguaro 4-12 m tall, 0.4 m thick, arms rising from 2-4 m up',
    parts: ['vertical RIBS running the full height', 'arms that rise vertically after bending out', 'spines along every rib', 'a flat rounded top, never a point'],
    tell: 'The vertical ribbing and the arms that turn UP. A smooth green cylinder with stubs is a bollard.' },
];

/** Stone. */
const ROCKS: CatalogEntry[] = [
  { id: 'rock', name: 'rock / boulder', category: 'rock',
    words: 'rock|rocks|boulder|stone|pathar|pebble|scree|rubble', hi: 'पत्थर|चट्टान',
    dims: 'pebbles 0.05-0.2 m, rocks 0.3-1.5 m, boulders 2-6 m; bury 20-40% of each one',
    parts: ['flat facets and sharp edges, never a smooth sphere', 'moss or dirt in the crevices', 'a stone material with strong bump and AO', 'random rotation so no two read as copies'],
    tell: 'A rock is FACETED and partly buried. A sphere sitting exactly on the ground is a ball.' },
  { id: 'log', name: 'log / stump / driftwood', category: 'rock',
    words: 'log|stump|fallen\\s*tree|driftwood|firewood|lakdi', hi: 'लकड़ी',
    dims: 'a fallen log is 2-6 m long and 0.3-0.8 m thick; a stump 0.4-1.2 m tall',
    parts: ['visible growth rings on the cut end', 'bark on the outside and bare wood where it is broken', 'a taper along the length', 'moss on the upper surface only', 'partly sunk into the ground with leaf litter around it'],
    tell: 'The RINGS on the cut end. A brown cylinder is a pipe.' },
];

/** Sky. */
const SKY: CatalogEntry[] = [
  { id: 'cloud', name: 'cloud', category: 'sky',
    words: 'cloud|clouds|badal|cumulus|overcast|sky', hi: 'बादल|आसमान',
    dims: 'cumulus 1-3 km across, based at 1-2 km altitude; render at scene scale 300-1000 units wide',
    parts: ['a BUILT-UP shape from many overlapping soft volumes, never one puff', 'a flat, darker base and a bright cauliflower top', 'varied sizes and spacing across the sky', 'slow continuous drift', 'colour taken from the lighting preset — warm at sunset, grey when overcast'],
    tell: 'The FLAT BASE. Real clouds sit on an invisible shelf at one altitude; uniformly round puffs read as cotton wool.' },
  { id: 'sun-moon', name: 'sun / moon / stars', category: 'sky',
    words: 'sun|sunlight|moon|moonlight|stars|night\\s*sky|suraj|chand|tara', hi: 'सूरज|चांद|तारे',
    dims: 'sun and moon both subtend half a degree — about 1/100th of the sky width; place them at the far plane',
    parts: ['a disc far smaller than people expect', 'a glow around it, not a hard-edged circle', 'the KEY LIGHT direction matching the disc position exactly', 'stars only as small points of varied brightness', 'the sky gradient agreeing with the time of day'],
    tell: 'The light direction must match where the sun is DRAWN. A sun in the sky with shadows falling the other way is the error everyone feels and nobody names.' },
  { id: 'weather', name: 'rain / fog / lightning', category: 'sky',
    words: 'rain|rainy|storm|thunder|lightning|fog|mist|barish|toofan|kohra|monsoon', hi: 'बारिश|तूफान|कोहरा|बिजली',
    dims: 'rain streaks 0.3-0.8 m long falling at 8 m/s; fog visibility 20-200 m; a lightning flash lasts 0.1-0.3 s',
    parts: ['rain as streaks near the camera PLUS a full-screen haze, not individual drops', 'splashes and ripples where it lands', 'wet, more reflective surfaces while it rains', 'fog colour matching the sky, never grey over a blue sky', 'a lightning flash that briefly changes the SCENE light, not just the sky'],
    tell: 'Rain must change the WORLD — wet reflective ground, reduced visibility, sound. Particles falling over a dry sunny scene look like a screen overlay.' },
];

/** Built things. */
const BUILDINGS: CatalogEntry[] = [
  { id: 'house', name: 'house / hut', category: 'building',
    words: 'house|home|hut|jhopdi|bungalow|makaan|ghar|cottage|villa|farmhouse', hi: 'घर|मकान|झोपड़ी',
    dims: '9 m x 8 m, walls 3.0 m, roof ridge 4.5 m; door 2.1 m x 0.9 m; window 1.2 m x 1.2 m with a 1.0 m sill',
    parts: ['a roof with real OVERHANG past the walls', 'a door at human scale (2.1 m)', 'windows at a consistent sill height', 'a visible plinth or step at the base', 'a wall material with bump, never one flat colour', 'a chimney, water tank or antenna on the roof'],
    tell: 'The door proves the scale of everything else. A roof flush with the walls is what makes a house look like a packing crate.' },
  { id: 'apartment', name: 'apartment block / skyscraper', category: 'building',
    words: 'apartment|flats|tower|skyscraper|high\\s*rise|building|office\\s*block', hi: 'इमारत|बिल्डिंग|अपार्टमेंट',
    dims: 'floor-to-floor 3.0 m, so a 10-storey block is 30 m; a skyscraper 100-400 m; footprint 20-40 m',
    parts: ['a REPEATING floor band at exactly 3.0 m', 'a ground floor that differs from the rest — taller, shops, an entrance', 'balconies, ledges or mullions breaking the flat face', 'a roof with plant, tanks and railings, never a clean plane', 'windows as dark reflective glass, not bright flat panels'],
    tell: 'The 3 m floor rhythm is how the eye counts storeys and reads the height. A tall box with random windows has no readable scale at all.' },
  { id: 'shop', name: 'shop / market stall', category: 'building',
    words: 'shop|store|stall|market|bazaar|dukaan|kirana|shopping', hi: 'दुकान|बाज़ार|बाजार',
    dims: 'a small shop front is 3-5 m wide, 3 m tall, 4-6 m deep; a stall 2 m x 2 m with a 2.2 m canopy',
    parts: ['an OPEN front — a shutter rolled up, or no wall at all', 'a signboard above the opening', 'goods stacked and visible from the street', 'an awning or canopy over the pavement', 'a step up from the street'],
    tell: 'The open front and the sign. A closed box with a door is a house with a poster on it.' },
  { id: 'temple', name: 'temple / mosque / church', category: 'building',
    words: 'temple|mandir|mosque|masjid|church|gurudwara|shrine|pagoda|stupa', hi: 'मंदिर|मस्जिद|गुरुद्वारा',
    dims: 'a village temple 6 m x 6 m with a 9-12 m shikhar; a mosque dome 8-15 m across; a church spire 20-40 m',
    parts: ['a distinctive vertical feature — shikhar, dome, spire or minaret', 'a raised plinth with steps', 'an entrance on one clear axis', 'carved or patterned surface detail rather than plain walls', 'a courtyard or forecourt'],
    tell: 'The vertical feature IS the building — it is what makes it visible from across the level. A box with a small dome reads as a water tank.' },
  { id: 'civic-building', name: 'school / hospital / station / factory', category: 'building',
    words: 'school|college|hospital|clinic|station|railway\\s*station|bus\\s*stand|factory|warehouse|godown|airport', hi: 'स्कूल|अस्पताल|स्टेशन|कारखाना',
    dims: 'a school block 40 m x 12 m, two or three storeys; a factory shed 60 m x 25 m x 9 m with a 6 m door',
    parts: ['a LONG repeating facade — many identical bays', 'a clearly marked main entrance breaking the repetition', 'a functional roof: north lights or trusses on a shed, tanks on a block', 'a boundary wall, gate and a sign', 'a forecourt, yard or parking area'],
    tell: 'Repetition plus ONE break for the entrance. Pure repetition is a wall; no repetition is a house.' },
  { id: 'bridge', name: 'bridge', category: 'building',
    words: 'bridge|flyover|overpass|pul|viaduct', hi: 'पुल',
    dims: 'a road bridge deck is 8-12 m wide, spans 20-60 m between piers, and clears 5-8 m over water',
    parts: ['piers or abutments carrying the deck down to the ground or the riverbed', 'a parapet or railing along both edges', 'a deck thickness of 0.8-1.5 m, never a paper-thin plane', 'the road surface continuing across without a seam', 'a visible structural system — arch, truss or girder'],
    tell: 'It must be SUPPORTED. A deck floating between two banks with nothing under it is the commonest bridge mistake.' },
  { id: 'wall', name: 'wall / fence / gate', category: 'building',
    words: 'wall|fence|boundary|compound|gate|railing|barrier|deewar|chardiwari', hi: 'दीवार|बाड़|गेट',
    dims: 'a compound wall 1.8-2.4 m tall, 0.23 m thick; a fence post every 2.5 m; a gate 3-4 m wide',
    parts: ['a coping or cap along the top', 'posts or pillars at regular intervals', 'a base that follows the ground, stepping on a slope', 'weathering — stains, moss, peeling paint', 'a gate that reads as openable, with hinges and a latch'],
    tell: 'It must STEP down a slope, not float or sink. A wall whose base ignores the terrain is the most visible placement error there is.' },
  { id: 'tent', name: 'tent / shed / canopy', category: 'building',
    words: 'tent|camp|shamiana|pandal|canopy|shed', hi: 'तंबू|शामियाना|पंडाल',
    dims: 'a camping tent 2.2 m x 1.4 m x 1.1 m; an event shamiana 10 m x 10 m with a 3.5 m eave',
    parts: ['fabric that SAGS between its supports, never flat panels', 'poles and guy ropes under tension', 'pegs where the ropes meet the ground', 'an entrance flap', 'light passing through the fabric'],
    tell: 'Fabric sags. Perfectly flat triangular panels read as folded card.' },
];

export const CATALOG_PART_2: CatalogEntry[] = [
  ...TERRAIN, ...WATER, ...VEGETATION, ...ROCKS, ...SKY, ...BUILDINGS,
];

/** The small repeated things that turn an empty road into a place. */
const STREET: CatalogEntry[] = [
  { id: 'streetlight', name: 'streetlight / lamp post', category: 'street-prop',
    words: 'street\\s*light|streetlight|lamp\\s*post|lamppost|street\\s*lamp|pole\\s*light', hi: 'स्ट्रीट\\s*लाइट|खंभा',
    dims: '9 m tall, arm reaching 1.8 m over the road, spaced every 25-30 m, alternating sides',
    parts: ['a tapered pole, thicker at the base', 'a curved arm reaching over the carriageway', 'a lamp housing angled DOWN at the road', 'an emissive lamp plus a real or faked pooled light on the road at night', 'a concrete base or bolted flange'],
    tell: 'The arm reaches over the ROAD and the light points down. A vertical pole with a glowing ball on top is a garden lamp.' },
  { id: 'traffic-light', name: 'traffic light / road sign', category: 'street-prop',
    words: 'traffic\\s*light|signal|traffic\\s*signal|road\\s*sign|sign\\s*board|signboard|milestone|hoarding|billboard',
    hi: 'ट्रैफिक\\s*लाइट|साइन\\s*बोर्ड|होर्डिंग',
    dims: 'signal head 0.9 m tall on a 3-6 m pole; a road sign face 0.6-0.9 m at 2.1 m; a billboard 6 m x 3 m at 5 m',
    parts: ['only ONE lamp lit at a time, and it changes on a timer', 'each lamp emissive, with the unlit ones genuinely dark', 'a sign face turned to FACE the oncoming traffic', 'a pole with a visible base plate', 'reflective sheeting that catches headlights at night'],
    tell: 'A signal with all three lamps glowing at once is the most common careless detail in generated street scenes.' },
  { id: 'bench', name: 'bench / dustbin / street furniture', category: 'street-prop',
    words: 'bench|dustbin|trash\\s*can|bin|litter|hydrant|bollard|planter|kiosk', hi: 'बेंच|कूड़ेदान',
    dims: 'bench seat 0.45 m high, 1.8 m long; dustbin 0.9 m tall, 0.5 m across; bollard 0.9 m tall',
    parts: ['legs or a base that meets the pavement exactly', 'slats, ribs or panels rather than a solid block', 'wear and grime concentrated where people touch it', 'a fixed orientation — benches face the view, bins face the path'],
    tell: 'Seat height 0.45 m. A bench at the wrong height makes every person who sits on it look wrong, and nobody can say why.' },
  { id: 'power-line', name: 'electric pole / wires', category: 'street-prop',
    words: 'electric\\s*pole|power\\s*line|wires|telephone\\s*pole|transmission|cable', hi: 'बिजली\\s*का\\s*खंभा|तार',
    dims: 'poles 8-11 m tall every 40-60 m; wires SAG 0.5-1.5 m between them',
    parts: ['wires that SAG in a catenary curve, never straight lines', 'cross-arms with insulators', 'several wires at different heights', 'a transformer or junction box on some poles', 'stay wires anchored to the ground'],
    tell: 'The SAG. Perfectly straight wires between poles is the single most artificial thing in an outdoor scene.' },
  { id: 'barrier', name: 'cone / barricade / speed breaker', category: 'street-prop',
    words: 'cone|barricade|barrier|road\\s*block|speed\\s*breaker|speed\\s*bump|divider|guard\\s*rail',
    hi: 'बैरिकेड|स्पीड\\s*ब्रेकर|डिवाइडर',
    dims: 'cone 0.75 m tall with a 0.36 m base; barricade 1.0 m x 2.0 m; speed breaker 0.1 m high, 3.7 m across',
    parts: ['high-visibility bands in alternating colours', 'a weighted base that sits flat', 'reflective strips', 'a slight lean or knock-over on a few, so the row is not perfect'],
    tell: 'A perfectly aligned identical row is a fence. Knock one over and vary the spacing and it becomes a road.' },
  { id: 'well', name: 'well / hand pump / water tank', category: 'street-prop',
    words: 'well|handpump|hand\\s*pump|borewell|water\\s*tank|tanki|nal', hi: 'कुआं|कुआँ|हैंडपंप|पानी\\s*की\\s*टंकी',
    dims: 'a village well is 1.5-3 m across with a 0.9 m parapet; a hand pump 1.3 m tall; an overhead tank 2-5 m across on 6-12 m legs',
    parts: ['a raised parapet or platform you cannot fall into', 'a wet, stained, algae-marked surface near the water', 'a pulley and rope, or a pump handle and spout', 'a drainage channel leading away', 'worn stone where hands and feet go'],
    tell: 'The WET staining around it. A clean dry well reads as a decorative ring.' },
];

/** Inside a room. */
const INTERIOR: CatalogEntry[] = [
  { id: 'table', name: 'table / desk / counter', category: 'interior',
    words: 'table|desk|counter|worktop|mez|dining\\s*table', hi: 'मेज़|मेज|टेबल',
    dims: 'dining table 0.75 m high, 1.8 m x 0.9 m; desk 0.75 m; kitchen counter 0.90 m; coffee table 0.45 m',
    parts: ['a top thinner than it looks tempting to make — 0.03-0.05 m', 'legs inset from the corners, not flush', 'a rail or apron under the top', 'a material with real grain, never flat brown'],
    tell: 'Every table in the world is 0.75 m high. Get that one number right and the whole room reads correctly.' },
  { id: 'chair', name: 'chair / sofa / stool', category: 'interior',
    words: 'chair|sofa|couch|stool|seat|armchair|kursi|bench\\s*seat', hi: 'कुर्सी|सोफा',
    dims: 'seat 0.45 m high, 0.45 m deep; back 0.85 m from the floor; sofa 2.0 m x 0.9 m, seat 0.42 m',
    parts: ['a back RECLINED slightly, never vertical', 'a seat with visible thickness and give', 'legs or a plinth meeting the floor exactly', 'arms at 0.65 m if it has them', 'cushion seams or upholstery texture'],
    tell: 'Seat 0.45 m and a reclined back. A vertical-backed box at the wrong height makes a room look like a waiting hall.' },
  { id: 'bed', name: 'bed', category: 'interior',
    words: 'bed|mattress|bunk|palang|charpai', hi: 'बिस्तर|पलंग|चारपाई',
    dims: 'double 2.0 m x 1.5 m, mattress top 0.55 m from the floor; single 1.9 m x 0.9 m',
    parts: ['a mattress with visible thickness (0.2 m) sitting on a frame', 'a headboard taller than the mattress', 'bedding that DRAPES over the edges rather than ending flat', 'a pillow with a dent', 'a gap under the frame'],
    tell: 'Bedding must drape and crease. A flat rectangle of colour on a box is a table with a blanket printed on it.' },
  { id: 'door', name: 'door / window', category: 'interior',
    words: 'door|doorway|window|darwaza|khidki|gate\\s*door', hi: 'दरवाज़ा|दरवाजा|खिड़की',
    dims: 'door 2.1 m x 0.9 m, leaf 0.04 m thick; window 1.2 m x 1.2 m with a 1.0 m sill; frame 0.05 m',
    parts: ['a FRAME set into the wall, with the leaf inside it', 'a handle at 1.0 m and visible hinges on one side', 'panels or glazing bars breaking the flat leaf', 'a threshold at the floor', 'a shadow line where the leaf sits back from the frame'],
    tell: 'A door without a frame is a painted rectangle. The frame and the 1.0 m handle are what make it openable to the eye.' },
  { id: 'shelf', name: 'shelf / cupboard / almirah', category: 'interior',
    words: 'shelf|shelves|cupboard|almirah|wardrobe|cabinet|rack|bookshelf', hi: 'अलमारी|शेल्फ',
    dims: 'shelves every 0.3-0.35 m; a cupboard 2.0 m tall, 1.0 m wide, 0.55 m deep; a book 0.24 m tall',
    parts: ['contents — books, boxes, vessels — never an empty grid', 'shelf boards with visible thickness', 'a back panel so you do not see the wall through it', 'doors or a frame, with handles', 'items at varied heights and angles'],
    tell: 'It must be FULL, and untidily so. An empty shelf grid is the clearest "unfinished level" signal there is.' },
  { id: 'appliance', name: 'TV / computer / fridge / stove', category: 'interior',
    words: 'tv|television|monitor|computer|laptop|fridge|refrigerator|stove|oven|washing\\s*machine|fan|ac',
    hi: 'टीवी|कंप्यूटर|फ्रिज|चूल्हा|पंखा',
    dims: 'TV 1.2 m wide at 1.0 m centre height; fridge 1.7 m x 0.6 m x 0.65 m; stove counter 0.9 m; ceiling fan 1.2 m span at 2.6 m',
    parts: ['a SCREEN that is dark and slightly reflective when off, emissive when on', 'a bezel or frame around the screen', 'a stand, bracket or feet', 'buttons, vents, handles and a cable', 'the cable actually reaching a socket'],
    tell: 'A screen must either be dark and reflective or genuinely emissive. A flat grey rectangle is the commonest fake appliance.' },
  { id: 'light-fixture', name: 'lamp / light fitting', category: 'interior',
    words: 'lamp|light\\s*bulb|bulb|chandelier|tube\\s*light|lantern|torch|diya|candle', hi: 'लैंप|बल्ब|दीया|मोमबत्ती',
    dims: 'a table lamp 0.45 m tall; a pendant hung 0.75 m above a table; a bulb 0.06 m',
    parts: ['an emissive element AND a real light in the scene at the same position', 'a shade or housing that shapes where the light falls', 'a warm colour for tungsten, cooler for daylight', 'a visible cable, chain or stem', 'a pool of light on the nearest surface'],
    tell: 'The emissive mesh and the actual light must be in the SAME place. A glowing bulb that lights nothing, or a lit room with no visible source, both read as broken.' },
];

/** Games within games. */
const SPORT: CatalogEntry[] = [
  { id: 'cricket', name: 'cricket equipment', category: 'sport',
    words: 'cricket|batting|bowler|wicket|ipl|stumps|crease', hi: 'क्रिकेट',
    dims: 'bat 0.96 m long with a 0.108 m blade; ball 0.072 m across; stumps 0.71 m tall and 0.229 m over all three; pitch 20.12 m; boundary 60-75 m',
    parts: ['a bat with a distinct handle, shoulder and swell toward the toe', 'a seam around the ball', 'THREE stumps with two bails resting on top', 'creases marked on the pitch surface', 'a worn pitch strip different from the outfield'],
    tell: 'The blade is only 10.8 cm wide — far narrower than people build it — and it is flat on the face and ridged on the back.' },
  { id: 'ball', name: 'ball', category: 'sport',
    words: 'football|soccer|basketball|volleyball|tennis\\s*ball|ball\\s*game|gend', hi: 'फुटबॉल|गेंद|बास्केटबॉल',
    dims: 'football 0.22 m across; basketball 0.24 m; volleyball 0.21 m; tennis ball 0.067 m; hockey ball 0.073 m',
    parts: ['a panel or seam pattern, never a plain sphere', 'a matte or lightly textured surface that catches light unevenly', 'a contact shadow directly beneath it', 'visible spin while it travels'],
    tell: 'A plain untextured sphere is the flattest object it is possible to render, and the panel lines are the whole read. It must also SPIN — a ball travelling without rotation reads as a bubble.' },
  { id: 'goal', name: 'goal / hoop / net', category: 'sport',
    words: 'goal\\s*post|goalpost|goal|hoop|basket|net|nets|racket|bat\\s*and\\s*ball', hi: 'गोल\\s*पोस्ट|नेट',
    dims: 'football goal 7.32 m x 2.44 m; basketball hoop 3.05 m high with a 0.45 m ring; a tennis net 0.914 m at the centre',
    parts: ['a net that SAGS and moves when struck', 'a frame of real thickness anchored to the ground', 'the exact regulation size', 'ground markings meeting it correctly'],
    tell: 'The net must move. A rigid mesh sheet turns every goal into a cardboard cut-out at the moment it matters most.' },
  { id: 'track', name: 'race track / arena / pool', category: 'sport',
    words: 'race\\s*track|racetrack|circuit|arena|stadium|swimming\\s*pool|court|pitch\\s*ground|running\\s*track',
    hi: 'स्टेडियम|ट्रैक|मैदान',
    dims: 'athletics lane 1.22 m wide, 400 m lap; a swimming pool 25 or 50 m with 2.5 m lanes; a stadium stand rises at 20-35 degrees',
    parts: ['lane or boundary markings ON the surface', 'a banked or kerbed edge', 'tiered seating rising away from the field', 'floodlight masts at the corners', 'a surface material different from the surroundings'],
    tell: 'The stands must RISE steeply enough that the back row can see. A flat ring of seats around a field reads as a car park.' },
];

/** Things characters hold. */
const WEAPONS: CatalogEntry[] = [
  { id: 'sword', name: 'sword / axe / blade', category: 'weapon',
    words: 'sword|blade|katana|talwar|sabre|saber|axe|kulhadi|dagger|knife|spear|trishul', hi: 'तलवार|कुल्हाड़ी|भाला',
    dims: 'sword 1.00 m overall, blade 0.80 m x 0.05 m tapering to a point, grip 0.15 m; axe 0.9 m haft; spear 2.1 m',
    parts: ['a blade with a visible edge bevel, never a flat slab', 'a crossguard wider than the grip', 'a wrapped grip', 'a pommel counterweight', 'an off-centre head with a bit and a poll (axe)'],
    tell: 'The blade TAPERS in both width and thickness toward the point. A constant-width box is a ruler.' },
  { id: 'gun', name: 'firearm', category: 'weapon',
    words: 'gun|rifle|pistol|shooter|shooting\\s*game|sniper|ak\\s*-?\\s*47|shotgun|revolver', hi: 'बंदूक|राइफल|पिस्तौल',
    dims: 'rifle 1.00 m long, barrel 0.50 m, magazine 0.25 m; pistol 0.20 m; a bullet leaves at 800 m/s',
    parts: ['a barrel clearly THINNER than the receiver', 'a magazine below the receiver', 'a pistol grip and trigger guard', 'a stock against the shoulder (rifle)', 'iron sights or an optic on top', 'a muzzle the effects fire from'],
    tell: 'Thin barrel, thick receiver, grip at an angle to both. One tapered box reads as a plank.' },
  { id: 'bow', name: 'bow / sling / thrown weapon', category: 'weapon',
    words: 'bow\\s*and\\s*arrow|bow|arrow|archery|crossbow|catapult|sling|grenade|dhanush', hi: 'धनुष|तीर',
    dims: 'bow 1.7 m tall with a 0.55 m draw; arrow 0.75 m; a grenade 0.09 m across',
    parts: ['limbs that BEND when drawn, and straighten when released', 'a string thinner than the limbs, under visible tension', 'an arrow with a head, shaft and fletching', 'a grip at the centre', 'a nocking point'],
    tell: 'The limbs must flex with the draw. A rigid arc with a line across it is a decoration on a wall.' },
  { id: 'shield', name: 'shield / armour', category: 'weapon',
    words: 'shield|armou?r|helmet|breastplate|gauntlet|dhaal', hi: 'ढाल|कवच',
    dims: 'round shield 0.6-0.9 m across, 0.03 m thick; a helmet adds 0.06 m to a head',
    parts: ['a curved face, never a flat disc', 'a rim or edging of a different material', 'straps and a grip on the inside', 'battle damage — dents, scratches, chipped paint', 'a boss or central reinforcement'],
    tell: 'The CURVE plus the damage. A flat clean disc is a table top being carried.' },
];

/** What the player picks up. */
const COLLECTIBLES: CatalogEntry[] = [
  { id: 'coin', name: 'coin / gem / star', category: 'collectible',
    words: 'coin|coins|gem|jewel|crystal|star\\s*pickup|point|score\\s*item|sikka|treasure|gold', hi: 'सिक्का|रत्न|खज़ाना',
    dims: 'a coin reads at 0.35-0.5 m in-game (far larger than a real one); a gem 0.3 m; float 0.5 m above the ground',
    parts: ['an emissive or metallic material with something to reflect', 'a face detail — a symbol, facets, a rim', 'a glow, sparkle or small light', 'thickness: a coin is a short cylinder, never a flat disc'],
    tell: 'Game pickups are deliberately OVERSIZED and they spin. A real-scale coin lying still on the floor is invisible to a player and will never be collected.' },
  { id: 'key', name: 'key / chest / door lock', category: 'collectible',
    words: 'key|keys|chest|treasure\\s*box|lock|locker|safe|chaabi|sandook', hi: 'चाबी|संदूक',
    dims: 'a chest 0.9 m x 0.5 m x 0.5 m; a game key reads at 0.3 m; a padlock 0.15 m',
    parts: ['a lid with a HINGE that visibly opens', 'metal banding over a different body material', 'a lock plate or keyhole', 'contents revealed when opened, not an empty box', 'wear on the corners and the lid edge'],
    tell: 'It must open. A sealed box with a keyhole painted on is the single most disappointing object in a level.' },
  { id: 'powerup', name: 'power-up / health / potion', category: 'collectible',
    words: 'power\\s*up|powerup|health\\s*pack|heart|potion|elixir|boost|shield\\s*pickup|ammo|fuel\\s*pickup',
    hi: 'पावर\\s*अप|दवा',
    dims: 'reads at 0.4-0.6 m, floating 0.5 m up, rotating one turn every 2-4 seconds',
    parts: ['a colour that means its effect and NOTHING else in the level shares', 'an emissive core or an internal glow', 'a distinct silhouette readable from 20 m', 'a bob-and-spin animation', 'a burst effect plus a sound on pickup'],
    tell: 'Colour-code by EFFECT and never reuse those colours for scenery. A player must know what a pickup does before they reach it.' },
  { id: 'marker', name: 'checkpoint / portal / marker', category: 'collectible',
    words: 'checkpoint|portal|spawn|waypoint|marker|flag|finish\\s*line|goal\\s*marker|teleport', hi: 'चेकपॉइंट|झंडा',
    dims: 'a checkpoint gate 4-6 m wide and 4 m tall; a floor pad 2 m across; a flag 2.5 m tall',
    parts: ['a shape readable from a DISTANCE and from any angle', 'an animated element — a rotating ring, a rippling surface, a waving flag', 'a clear before/after state so the player knows it triggered', 'a light or emissive so it is visible in every lighting preset'],
    tell: 'It must be legible from across the level and it must visibly CHANGE when used. A static prop the player cannot tell they have activated is a bug report waiting to happen.' },
];

/** Boxes and the things in them. */
const CONTAINERS: CatalogEntry[] = [
  { id: 'crate', name: 'crate / barrel / box', category: 'container',
    words: 'crate|barrel|box|boxes|cargo|container\\s*box|drum|sack|bora|pallet', hi: 'पेटी|डिब्बा|बोरा|ड्रम',
    dims: 'crate 1.0 m cube; oil drum 0.88 m tall x 0.58 m across; a sack 0.8 m x 0.5 m; a pallet 1.2 m x 1.0 m',
    parts: ['planks, ribs, bands or a rim breaking the plain shape', 'a lid or top that reads as removable', 'wear at the corners and along the base', 'stencilled markings or a label', 'a sack that SAGS with its contents rather than holding a shape'],
    tell: 'A bare cube is the flattest object it is possible to place. The planks and the corner wear are the entire difference.' },
  { id: 'basket', name: 'basket / pot / vessel', category: 'container',
    words: 'basket|pot|matka|vessel|bucket|jar|bottle|can|tokri|handi', hi: 'टोकरी|मटका|बाल्टी|बोतल',
    dims: 'a basket 0.5 m across x 0.35 m; a matka 0.4 m across; a bucket 0.3 m; a bottle 0.25 m tall',
    parts: ['a RIM that is thinner than the body', 'a hollow interior visible from above, never a solid lump', 'a handle, neck or lip', 'a woven, thrown or moulded surface texture', 'contents if it is in use'],
    tell: 'It must be HOLLOW at the top. A solid shape with a basket texture is a rock.' },
];

/** Food. */
const FOOD: CatalogEntry[] = [
  { id: 'fruit', name: 'fruit / vegetable', category: 'food',
    words: 'fruit|apple|mango|banana|vegetable|sabzi|tomato|potato|coconut|orange', hi: 'फल|सब्ज़ी|सब्जी|आम|केला',
    dims: 'apple 0.08 m, mango 0.12 m, banana 0.18 m, coconut 0.15 m, watermelon 0.30 m',
    parts: ['a stem, calyx or crown — never a bare ball', 'an asymmetric shape, slightly dented', 'colour variation across the surface, not one flat tone', 'a small specular sheen on the skin'],
    tell: 'Check it against a 0.18 m hand. Food is the easiest thing in a game to build twice too large, and a plain sphere is a marble.' },
  { id: 'meal', name: 'cooked food / plate / drink', category: 'food',
    words: 'food|meal|plate|thali|roti|rice|curry|cake|bread|tea|chai|cup|glass\\s*drink|snack',
    hi: 'खाना|थाली|रोटी|चाय|केक',
    dims: 'plate 0.26 m across; thali 0.30 m; cup 0.08 m tall; a roti 0.18 m; a cake 0.20 m',
    parts: ['a plate or vessel UNDER the food, never food floating on a table', 'food in separate portions with different materials', 'steam if it is hot', 'a glossy or wet sheen on anything cooked', 'a spoon, fork or hand nearby for scale'],
    tell: 'Real food is glossy and irregular. Matte identical shapes read as plastic display food in a restaurant window.' },
];

/** Things that happen rather than exist. */
const EFFECTS: CatalogEntry[] = [
  { id: 'fire', name: 'fire / explosion / smoke', category: 'effect',
    words: 'fire|flame|explosion|blast|smoke|bomb|burning|dhamaka|aag|campfire', hi: 'आग|धमाका|धुआं|विस्फोट',
    dims: 'a campfire flame 0.5 m tall; an explosion fireball 3-8 m across lasting 0.4 s; a smoke column rising 10-30 m',
    parts: ['additive blending with depthWrite OFF', 'a real LIGHT that flickers and tints the surroundings', 'smoke that outlives the flame and rises, expanding and thinning', 'sound plus a camera shake plus a split-second freeze, fired together', 'embers or debris thrown outward'],
    tell: 'Fire must LIGHT its surroundings. An orange sprite on a dark scene is a sticker; the flicker on nearby walls is what makes it real.' },
  { id: 'splash', name: 'splash / dust / sparks', category: 'effect',
    words: 'splash|dust|sparks|debris|trail|skid|tyre\\s*mark|footprint|ripple|chhinta', hi: 'छींटा|धूल|चिंगारी',
    dims: 'a footstep dust puff 0.3 m; a water splash 1-2 m; sparks fly 1-3 m and last 0.3 s',
    parts: ['particles spawned at the CONTACT POINT, never at an object centre', 'motion inherited from whatever caused it', 'gravity, so they arc and settle', 'a mark left behind — a wet patch, a skid, a print — that fades', 'fading by opacity AND scale together'],
    tell: 'It must start exactly where the contact happened and inherit that motion. Particles appearing at an object centre is the classic giveaway.' },
];

export const CATALOG_PART_3: CatalogEntry[] = [
  ...STREET, ...INTERIOR, ...SPORT, ...WEAPONS, ...COLLECTIBLES, ...CONTAINERS, ...FOOD, ...EFFECTS,
];

/**
 * THE WHOLE CATALOGUE. Split into three constants only so the file stays editable; consumers use this.
 *
 * ⚠️ Ordered so that a SPECIFIC entry is tested before a general one where they could both match —
 * `heroObjectContract` takes the first few matches, and "bike racing game" must find the motorcycle
 * before it finds the road it runs on.
 */
export const OBJECT_CATALOG: readonly CatalogEntry[] = Object.freeze([
  ...CATALOG_PART_1, ...CATALOG_PART_2, ...CATALOG_PART_3,
]);
